launchable/commands/record/build.py, launchable/commands/record/commit.py, launchable/utils/ingester_jar.py, requirements.txt
- Add `--executable` option to the `commit` command
- It has `jar` and `docker` options. `jar` is the default.
- Download `exec_deploy.jar` if it doesn't exist
- I added versioning to `exec_deploy.jar` on S3 and local. Do you agree it works well?
- I added `~/.launchable` as a jar cache directory. Do you think is this directory right place to store jar files?
=> Collecting commits without Docker

launchable/commands/record/commit.py, launchable/utils/http_client.py
Ingester has `-endpoint` flag which overrides its API host. To override the jar internal API host variable from the CLI, pass `LAUNCHABLE_BASE_URL` as a `-endpoint` flag.
=> Pass LAUNCHABLE_BASE_URL to Ingester jar file

launchable/__main__.py, launchable/commands/record/commit.py, launchable/commands/verify.py, launchable/utils/java.py
I implemented a verify command to test if the Launchable CLI is configured properly or not.
Success
```
Platform: macOS-10.15.7-x86_64-i386-64bit
Python version: 3.8.3
Java command: java
Your CLI configuration is successfully verified 🎉
```
Failure
```
Authentication failed. Most likely the value for LAUNCHABLE_TOKEN environment variable is invalid.
or 
Authentication failed. Most likely the value for the LAUNCHABLE_TOKEN environment variable is invalid.
or 
Java is not installed. You need Java to use the Launchable CLI.
```
=> Implement a verify command

launchable/commands/verify.py
Change to exit code 1 when the verify fails.
Makes it easier for the computer to determine success or failure.
(e.g. unix pipe processing)
for example:
```
$ laucnable verify && launchable record build --name BUILD_ID --source .
```
=> Change to exit code 1 when the verify fails

README.md
As per https://www.python.org/dev/peps/pep-0394/, as we require Python3, our instruction should be `pip3` to be more portable regardless of the Python version that `pip` resolves to.
=> We require Python3

launchable/commands/verify.py
It also shows the version of itself.
=> Show self version in verify

launchable/commands/optimize/test.py
When Error occurs, return the test name as it is passed. because We shud not stop build process.
SEE https://launchableinc.atlassian.net/browse/ST-634
=> Ignore API errors in optimize command

.github/workflows/python-package.yml, .github/workflows/python-publish.yml, README.md, launchable/version.py, requirements.txt, setup.py
We maintain two version representatives such as `/version.py` and [Git tags](https://github.com/launchableinc/cli/tags). This PR integrates them into Git tag via [setuptools_scm](https://pypi.org/project/setuptools-scm/).
=> Grab module version from Git tag

launchable/__main__.py, launchable/commands/optimize/__init__.py, launchable/commands/optimize/tests.py, launchable/commands/record/__init__.py, launchable/commands/record/tests.py, launchable/test_runners/bazel.py, launchable/test_runners/generic.py, launchable/test_runners/gradle.py, launchable/test_runners/launchable.py, launchable/utils/click.py
Based on our discussion Friday, here is my first shot at the extensibility to enable rapidly supporting lots of test runners with minimal effort.
From the user experience perspective, the key change here is to introduce one more layer of sub-command in `launchable optimize tests`. For example,
```
launchable optimize tests --target ... --session ... gradle path/to/testRoots
```
This will scan a directory recursively, find `*.java`, and massage file names to test names.
Another key story of the extensibility is that people who use "other" test runners can directly access our underlying capability, which is exposed as 'generic':
```
launchable optimize tests <options> generic test1 test2 test3
```
`test_runners` directory is meant to be the extensibility point. This is the directory where …
=> Better test runner support

launchable/commands/record/tests.py, launchable/utils/gzipgen.py
Buffering the entire request as string in memory and then sending it over is inefficient. In this change, I'm generating the payload incrementally.
Plus, use gzip content encoding in the payload, which our backend supports, to reduce the amount of  network traffic.
=> Stream request payload and compress it

launchable/commands/optimize/test.py, launchable/commands/record/test.py
Current `record test` and `optimize test` require `session_id`. However, if Launchable API caused an error in the session creation phase, those commands would be failed. To keep working customer's CI, I modified the CLI to ignore missing session_id.
=> Ignore session creation failure

launchable/commands/optimize/tests.py, launchable/commands/record/case_event.py, launchable/commands/record/tests.py, launchable/test_runners/bazel.py, launchable/test_runners/generic.py, launchable/test_runners/gradle.py, launchable/test_runners/minitest.py, launchable/testpath.py
In both `optimize tests` and `record tests`, tests are identified by their test paths.
Introduced an abstraction in the client to build test paths. For `optimize tests`, Optimize still access a string that looks like a file
name and builds a default test path. But this is currently not aligned with what `record tests` do, so something needs to change.
Bazel implementation & Gradle is now complete, and it demonstrates why this change was needed in the first place --- test paths reported by `record tests` should be a sub-path of those used by `optimize tests`
* Robustness: `optimize tests generic` to read tests from stdin
=> Pushed test name handling forward.

launchable/test_runners/bazel.py
On Bazel request, subsetting API returns a package and a target such as  ` [{"type":"package","name":"//src/test/java/com/ninjinkun"},{"type":"target","name":"mylib_test2\n"}]`. We need to format them to `/src/test/java/com/ninjinkun:mylib_test2`.
=> Add bazel subset formatter

launchable/commands/optimize/tests.py, launchable/utils/click.py
`--target 50%` instead of `--target 0.5`
(If this doesn't make it to the demo, that's OK. Trying not to rock the boat)
=> Percentage parameter

launchable/commands/subset.py
Turns out the default gets processed through the conversion code, instead of getting passed as-is.
=> Fixing up what I broke in PR #70

launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py
session ID is no longer a number, which was unnnecessary assumption anyway.
=> Capture the whole session path and remove the need for separate --name option

launchable/commands/record/case_event.py
Python returns a tuple from a tailing comma term such as `result = term_a,`!
=> Fix "record tests" is sending test names in an array

launchable/test_runners/googletest.py
This GoogleTest plugin support GoogleTest + CTest output and GoogleTest standalone + `--gtest_list_tests` output as shown below.
```shell
ctest -N
Test project /Users/ninjin/src/github.com/launchableinc/rocket-car-googletest
Test #1: FooTest.Bar
Test #2: FooTest.Baz
Test #3: FooTest.Foo
Test #4: */ParameterizedTest.Bar/*
Total Tests: 4
```
CTest sample is here https://github.com/launchableinc/rocket-car-googletest/pull/4
```shell
$ ./test_a --gtest_list_tests 
FooTest.
Bar
Baz
Foo
```
=> Add GoogleTest plugin

.github/workflows/python-package.yml, requirements.txt, setup.cfg, setup.py
I heard modern Python projects use `setup.cfg` instead of `setup.py` https://www.python.org/dev/peps/pep-0390/. Following this way, we can remove requirements.txt and some lines. According to my research, it is compatible for Python 3.4 or later under using setuptools 30.3.0 or later.
=> Move setup.py to setup.cfg

launchable/commands/record/tests.py, launchable/utils/http_client.py
My design goals here is to provide as much details as possible, given that our users are developers themselves.
Previously, the error message printed was:
```
<urllib3.connection.HTTPSConnection object at 0x7fbfc37eff70>: Failed to establish a new connection: [Errno -2] Name or service not known
```
which doesn't tell me what name failed to resolve. With this, the error is now:
```
File "/home/kohsuke/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
conn = connection.create_connection(
File "/home/kohsuke/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib/python3.8/socket.py", line 918, in …
```
=> Improving the error handling.

launchable/commands/subset.py, launchable/test_runners/go_test.py, tests/commands/test_record_tests_go_test.py, tests/data/go_test/record_test_result.json, tests/data/go_test/report.xml, tests/data/go_test/subset_result.json
`subset` command receives test names from stdin
```shell
go test -list . | launchable subset --name '#123' go_test > subset.txt
go test -run $(cat subset.txt | perl -anle 'print(join q{|}, map { q{^} . quotemeta . q{$} } @F)')
```
`record tests` command read JUnit XML files.
```shell
go test -v 2>&1 | go-junit-report >  report.xml # convert output via go-junit-report 
launchable record tests --name '#123' go_test .
```
Should the plugin command name be `go_test` or `go-test`?
=> Add Go test plugin

launchable/test_runners/launchable.py, tests/commands/test_record_tests_go_test.py
After discussing with @awilkes , we came to the agreement that more conventional command name is probably `go-test`.
While this is technically a breaking change, we haven't really announced the Go test support yet, so I think it's OK to sneak this in and call it v1.1.2
=> go_test -> go-test

launchable/commands/subset.py, launchable/test_runners/go_test.py, launchable/test_runners/googletest.py, launchable/test_runners/gradle.py, launchable/test_runners/launchable.py, launchable/test_runners/minitest.py, tests/cli_test_case.py, tests/commands/test_record_tests_go_test.py, tests/commands/test_record_tests_minitest.py, tests/data/go_test/record_test_result.json, tests/data/gradle/recursion/expected.json, tests/data/gradle/recursion/foo/bar/reports/1.xml, tests/test_runners/test_gradle.py
Also in this change,
* Make test code more DRY by introducing reusable base class `CliTestCase`
* Promote consistency across test runners by creating reusable `record tests` support
=> [ST-696] Accept XML file names, not just diirectories

launchable/test_runners/file.py
When I testing the file plugin, I noticed test_path contains a tailing new line like the one below:
```
testPaths: [[{"type":"file","name":"tests/dir1/test1.py\n"}], [{"type":"file","name":"tests/dir1/test2.py\n"}], [{"type":"file","name":"tests/dir2/test1.py\n"}], [{"type":"file","name":"tests/dir2/test2.py\n"}], [{"type":"file","name":"tests/dir3/test1.py"}]]
```
That is because the plugin takes the input as it is so I remove the tailing newline from it.
=> Remove tailing newlines from file plugin

launchable/commands/record/build.py, launchable/commands/record/tests.py
If we need/want to keep those to assist debugging, let's have the `--debug` flag.
=> Removing what appears to be the debug status code output.

CONTRIBUTING.md, setup.cfg
If users already use Python and have some libraries depend on Click, us needing the very latest could cause some pain.
Let's see if we can live with a little older Click 7.
=> Be more lax about the version of Click

launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py
In the latest main branch, `subset` command outputs a session ID to STDOUT. As a result, the output is mixed with a session ID and test names. I fixed it by suppressing printing a session ID.
```
$ cat ~/project/test/launchable/subset.txt
/intake/organizations/launchableinc/workspaces/rocket-car-minitest/builds/2717e8ed-e5f6-422d-a65d-4510942fc8c9/test_sessions/2476
test/controllers/user_test.rb
test/models/open_class_user_test.rb
test/models/user_copy_test.rb
test/models/user_test.rb
test/models/admin/user_test.rb
test/channels/application_cable/connection_test.rb
```
=> Surpress print session ID in the subset command

.github/workflows/python-package.yml, Pipfile, setup.cfg, tests/commands/test_verify.py, tests/test_version.py, tests/utils/test_gzipgen.py
We decided to use unittest as this CLI's test framework. I removed nose dependencies and add some unittest codes.
=> Replace nose with unittest

launchable/commands/record/tests.py, launchable/test_runners/cypress.py, tests/data/cypress/record_test_result.json, tests/data/cypress/subset_result.json, tests/data/cypress/test-result.xml, tests/test_runners/test_cypress.py
cypress JUnit reporter outputs incorrect format(https://github.com/cypress-io/cypress/issues/8237), so we can't use file command.
I create a cypress plugin for that.
I need some testsuites elements to get the test file name that use to report, so I define testsuites method that can overwrite.
And I prepare custom testsuites method for cypress.
outputed XML: https://github.com/launchableinc/cli/pull/101/files#diff-57f8b2c67ad176f3307742a51acc476264050670ebe13c6492441fd17596f971
=> [ST-704] add cypress test runner

launchable/commands/record/tests.py
I added debug option to print payloads for the record tests command.
I thought I would like to add debug option to global options, but the debug option only need for record tests.
So, I add debug options as the record tests command's option.
=> [ST-716] add debug option to print payload

launchable/commands/record/case_event.py, tests/data/googletest/fail/output.xml, tests/data/googletest/fail/record_test_result.json, tests/test_runners/test_googletest.py
Even though `junitparser.TestCase.result` is a type of [List](https://github.com/weiwei/junitparser/blob/master/junitparser/junitparser.py#L668-L669), compared TestResult with the result that is a List directly, so always status was a Success status before.
I'm wondering that should we set success status to status's initial value. 
Will you please comment on it?
=> [ST-726] fix handling for test cases result data

launchable/test_runners/launchable.py, tests/test_runners/test_googletest.py
https://github.com/launchableinc/cli/issues/103
Python's `"some_format" % some_string` needs `%s` in the format template such as `"some_format: %s" % some_string`. This is what caused #103 error.
=> Fix TypeError when file/glob does not match any file

docs/SUMMARY.md, docs/cli-reference.md, docs/getting-started.md, docs/integrations/always-run.md, docs/integrations/bazel.md, docs/integrations/cypress.md, docs/integrations/file.md, docs/integrations/go-test.md, docs/integrations/googletest.md, docs/integrations/gradle.md, docs/integrations/minitest.md
I found an issue. Most of CI system exits its run process when a test is failed. It means `record tests` after the test run doesn't run that time. To avoid this problem, customers must configure to run `record tests` after the test failed.
I propose the following setting. `trap` handles shell command signal. `0 1` are normal exit 0 and failure 1 (I think we can expect all test frameworks use this signal). 
```bash
trap "launchable record tests <BUILD NAME> [OPTIONS]" 0 1
bundle exec rails test -v $(cat tests.txt)
trap -
```
I want to add these instructions to the documents. I added some lines on this PR, but I think it's not enough. Please give me some idea about the following discussion point. 
There are other always run commands that depend on CI system. For example, Jenkins has [`post …
=> Add trap command lines to documents

launchable/test_runners/googletest.py, tests/data/googletest/subset_result.json, tests/test_runners/test_googletest.py
We have the new CTest plugin. To avoid confusion, I remove CTest support in the GoogleTest plugin. IIRC, the feature is undocumented and no customer uses it.
=> Remove CTest support from GoogleTest plugin

launchable/commands/record/tests.py
A common operator error is that zero tests are passed.
We do not fail in this case because it's possible that a catastrophic build failure occur before any tests run, leaving no test reports behind.
OTOH it's also possible during the setup that this simply points to a wrong location and we end up not collecting any test reports, so it's worth warning the user.
=> Test count diagnostics

launchable/commands/record/tests.py, tests/commands/record/test_tests.py, tests/data/broken.xml
A number of users repored problems while recording test results. When the parsing blows up, right now we don't know which file is offending, which makes the error diagnostics harder. Report the name of the offending file, so that we can pin down exactly which file is problematic.
=> For better diagnostics, report the path of the offending file

launchable/test_runners/ctest.py, tests/data/ctest/Testing/latest/Test.xml, tests/data/ctest/record_test_result.json
According to our customer, CTest XML format don't have `<NamedMeasurement name="Execution Time" />` element in skipped tests. I fixed CTest plugin to handle missing that element. Also, I added a converter that handles a `notrun` case as a skipped case.
=> Fix CTest to handle skipped case

launchable/commands/subset.py, launchable/test_runners/bazel.py, launchable/test_runners/ctest.py, launchable/test_runners/cypress.py, launchable/test_runners/file.py, launchable/test_runners/go_test.py, launchable/test_runners/googletest.py
- If we are reading stdin but it's not piped from a file/process, issue a warning. In a rare case this is intended (someone interactively debugging), but more often this is just a misunderstanding of the way CLI works, and an user mistakenly thinks that the CLI is hanging.
- If the server reports an error and we fall back, tell users we are doing that, again to avoid a surprise.
=> User friendliness improvements

launchable/utils/http_client.py
... so that a call will never hang and block people's builds/tests.
The connection time out is set aggressively, given that we have the
acess terminated at ALB and it's hard to imagine the pick up taking
longer than milliseconds order.
The read time out needs to be lax at the moment, mainly for `subset`
that might have to wait for a model to load, which is currently costly.
=> Set a time out

docs/SUMMARY.md, docs/getting-started.md, docs/optimizing-test-execution/subsetting-tests.md, docs/resources/cli-reference.md, docs/resources/convert-to-junit.md, docs/resources/integrations.md, docs/resources/troubleshooting.md, docs/resources/using-sessions-to-capture-test-reports-from-several-machines.md, docs/training-a-model/recording-builds.md, docs/training-a-model/recording-test-results.md
This change is best reviewed on the rendered version: https://launchable.gitbook.io/development/v/docs%2Frefactor-3/getting-started
- Split out "recording builds," "recording test results," and "subsetting test execution" into their own pages
- Move integration-specific instructions into the new "recording builds" and "subsetting test execution" pages to keep users from bouncing between pages
- Add a page that lists all the integrations, since the previous changes made it less clear
Out of scope:
- Other content updates (those will be handled in another PR)
=> Refactor docs structure

launchable/commands/record/tests.py, launchable/utils/http_client.py, tests/test_runners/test_cypress.py
From the latest change https://github.com/launchableinc/cli/pull/142, `record tests` command becames running many HTTP requests. To reduce those requests' overheads, introduce [requests's sessions](https://requests.readthedocs.io/en/master/user/advanced/).
This PR also includes Cypress tests refactoring because [`responses`](https://pypi.org/project/responses/) automatically mocks the session requests.
=> Send HTTP requests with sessions

launchable/commands/subset.py
Temporarily extend the timeout because the subset API response has been slow.
=> Set subset request timeout longer

launchable/commands/record/commit.py
My fault, `os.environ` isn't callable. I use `os.getenv()` instead of that.
=> Fix `record commit` command

launchable/commands/record/commit.py, tests/commands/record/test_commit.py
`https_proxy=http://foobar/` means browsers interested in connecting to an HTTPS site will first use plain HTTP to connect to foobar, then send an HTTP CONNECT command in plain text, then get a tunnel to the intended destination over which they initiate the TLS handshake.
I believe this is blocking a certain customer.
=> [ST-804] https_proxy might look like 'http://foobar/'

tests/commands/record/test_commit.py
[v1.5.6](https://github.com/launchableinc/cli/releases/tag/v1.5.6) caused syntax error. To prevent such errors, I added a simple test to invoke `record commit`.
=> Add `record commit` test

.github/workflows/python-publish.yml
Sent release notification to Launchble Discord with [a GithubAction plugin](https://github.com/marketplace/actions/actions-for-discord). This PR hasn't been tested yet because the action uses release payload information. I'll test it after it's merged.
=> Notify the CLI release to Launchable Discord through GithubAction

.github/workflows/python-publish.yml
Follow up for https://github.com/launchableinc/cli/pull/151. I fixed the misspecified module version. [0.3.0](https://github.com/Ilshidur/action-discord/releases) is the latest.
=> Specify correct action-discord version

launchable/__main__.py, launchable/utils/http_client.py, launchable/utils/logger.py, tests/utils/test_logger.py
I introduced a logger used by logging and set log levels default and audit. add a global option `--log-level` to change level for printing logs. when we only set the log level, the logger print log. 
I'd like to replace the @command.echo log output with this logger in the future.
when we set `log-level`, logs are printed like below,
```
$ LAUNCHABLE_TOKEN=XXX launchable --log-level audit subset --build sample-1  --target 10% maven ./src/test/java/com/example/app/App*
AUDIT:launchable:send request method:post path:/intake/organizations/<ORG>/workspaces/<WORKSPACE>/builds/sample-1/test_sessions headers:{'Content-Type': 'application/json'} args:{'timeout': (5, 60)}
AUDIT:launchable:send request method:post path:/intake/organizations/<ORG>/workspaces/<WORKSPACE>/subset …
```
=> [ST-796] Introduce logging logger and print audit log

.github/workflows/python-publish.yml
The Discord Github Action plugin didn't handle new line `\n` in the body. I remove them simply instead of research what escape char they accept.
=> Remove wrong chars from Discord post body

setup.cfg
We had specified junitparser v1.6.3 or later. However, the CLI code wasn't compatible with v1.6.3. We handled `TestCase.result` as a list in [here](https://github.com/launchableinc/cli/blob/b58eb1131cebc3f0f673c61b5543f9ee25b86671/launchable/commands/record/case_event.py#L49), but the version returned it as a single instance. It caused `TypeError("'NoneType' object is not iterable")`. Since junitparser v2.0.0 was shipped on Jan 11, most of our customers may use the version. But I assume a few earlier tried customers are still using v1.6.3. I convinced this is the cause of ST-817 because the error log also contained `TypeError("'Skipped' object is not iterable")`. It means this is related to the object from junitparser.
If you want to represent this error, do the following processes.
1. …
=> [ST-817]Fix `TypeError("'NoneType' object is not iterable")` error

launchable/commands/record/case_event.py, tests/data/googletest/output_a.xml, tests/data/googletest/record_test_result.json
JUnitPerser escape value in the JUnit XML by default. So, we need non escaped values in test names. Therefore, I modified the value handling to retrieve element value directly.
=> Avoid JUnitParser's value escaping 

.github/workflows/python-publish.yml
Current Discord release post has a wrong URL like https://api.github.com/repos/launchableinc/cli/releases/38715080. `release.html_url` returns collect release URL such as https://github.com/launchableinc/cli/releases/tag/v1.6.1
=> Fix GitHub URL in Discord post

launchable/commands/subset.py
before cli didn't expand the base path that includes magic words e.g `*`, `?`, etc
so, if the user sets the path that includes magic words, subset path will be broken.
```
$ launchable subset <SUBSET ARGS> '**/src/test/java'
--tests .com.launchableinc.rocket_car_gradle.AppTest2 --tests .com.launchableinc.rocket_car_gradle.AppTest --tests .com.launchableinc.rocket_car_gradle.sub.AppTest3 --tests ava.com.launchableinc.rocket_car_gradle.utils.UtilsTest
```
```
$ launchable subset <SUBSET ARGS> '**/src/test/java'
--tests com.launchableinc.rocket_car_gradle.AppTest2 --tests com.launchableinc.rocket_car_gradle.AppTest --tests com.launchableinc.rocket_car_gradle.sub.AppTest3 --tests com.launchableinc.rocket_car_gradle.utils.UtilsTest
```
=> support when base has magic

launchable/__main__.py, tests/plugins/foo.py, tests/test_plugin.py
To allow some customers to maintain custom test runner support more easily, define a mechanism to load test runner support from arbitrary user specified directory. This is also handy for rapid experiments.
=> Demonstration of the plugin loading mechanism

.github/workflows/python-package.yml
3.9.2 appears to be the current latest, so it should be in the test matrix.
=> Add Python 3.9 to testing matrix

launchable/commands/subset.py, tests/helper.py, tests/test_runners/test_gradle.py
`--split` option helps to introduce subsetting. if test framework support excluding, you should use it and subsetting list.
but some test frameworks don't support excluding so I add this option.
e.g) I tried the `--split` option to a maven project.
there are two test files
```sh
$ tree ./src/test/java/com/launchableinc/rocket_car_maven
./src/test/java/com/launchableinc/rocket_car_maven
├── App2Test.java
└── AppTest.java
```
first, tried to subset without the split option to check the subsetting result
```sh
$ launchable subset --build maven-1 --target 10% maven ./src/test/**
com.launchableinc.rocket_car_maven.AppTest
```
next, tried to subset with the split option and check results.
```sh
$ launchable subset --build maven-1 --target 10% --split subset.txt remainder.txt maven ./src/test/** …
```
=> [ST-831] support subset --split option

launchable/test_runners/gradle.py, launchable/utils/file_name_pattern.py, tests/data/gradle/java/app/src/test/java/com/launchableinc/rocket_car_gradle/App2Test.java, tests/data/gradle/java/app/src/test/java/com/launchableinc/rocket_car_gradle/sub/App3Test.java, tests/test_runners/test_gradle.py, tests/utils/test_file_name_pattern.py
The current Gradle plugin has a problem that it retrieves non-test files. To resolve it, I add test name heuristics such as `*Test.java`, `*Tests.java`, `*TestCase.java` (Of course I remained `.scala` and `.kt` support). These heuristics are based on [this reference](https://docs.gradle.org/current/userguide/java_testing.html).
=> Add Java Test name heuristics to the Gradle plugin

launchable/commands/subset.py, launchable/utils/click.py, tests/data/maven/subset_by_absolute_time_result.json, tests/test_runners/test_maven.py, tests/utils/test_click.py
I support absolute time-based subsetting.
e.g)
```sh
launchable subset --time 30m <SUBSET ARGS>
```
=> [ST-830] add time option for absolute time-based subsetting

launchable/utils/session.py, tests/test_session.py
we use unix session id as flavor to create session file. but when the cli run in the CircleCI, unix session id is changed each step.
so, I changed when the cli runs in the CircleCI, the cli uses the `CIRCLE_WORKFLOW_ID` instead of unix session id.
=> [ST-871] add patch to create session

launchable/commands/helper.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py, launchable/utils/session.py, tests/commands/test_helper.py, tests/test_session.py
I have made 2 changed in this PR
- show an error message when the request gets 404 error
- the commonality to setup session
If we request to create a session before record a build, got 404 error. But unfortunately, the error message isn't easy to understand what is the cause of the error now. So, I changed to show the message that what should we do.
Also, sometimes the subset command and the record tests get a 404 error. 
But I only added to the create session command and the record tests command, because the subset command gets 404 when the subset model doesn't create yet. https://github.com/launchableinc/cli/pull/183/commits/2c49478f38bc8d92c951398a483e57499562b685
```sh
$ LAUNCHABLE_TOKEN=<TOKEN> launchable record session  --build teeeeeeeeeeeest
404 Client Error:  for url: …
```
=> [ST-863] show warning message when request gets 404

launchable/commands/subset.py
before this change, if the test_path method receives test path strings which are contained wildcards, this method sets test_paths directly.
```sh
$ launchable subset --build 1 --target 20% minitest "test/**/*.rb"
test/**/*.rb
$ launchable subset --build 1 --target 20% minitest test/**/*.rb
test/application_system_test_case.rb
test/channels/application_cable/connection_test.rb
test/controllers/user_test.rb
test/models/admin/user_test.rb
test/models/open_class_user_test.rb
test/models/user_copy_test.rb
test/models/user_test.rb
test/test_h*ge.rb
test/test_helper.rb
```
so I fixed the test_path method expands wildcards 
```sh
$ launchable subset --build 1 --target 20% minitest "test/**/*.rb"
test/test_h*ge.rb
test/application_system_test_case.rb
test/test_helper.rb …
```
=> add check wildcard characters are contained or not

launchable/utils/java.py
To run `launchable verify` on Windows, I modified the code to use `shutil.which`.
Here is the command result.
```shell
PS C:\Users\IEUser> launchable verify
Organization: ninjinkun2
Workspace: oreore
Platform: Windows-10-10.0.17763-SP0
Python version: 3.9.4
Java command: java
launchable version: 1.13.3.dev7+g360b92b
Your CLI configuration is successfully verified
=> Run verify command on Windows

launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py, launchable/utils/click.py, tests/commands/record/test_session.py
before this change, the flavor option provides a `--flavor key value` format.
but the source option in the record build command provides a `--source repo=name` format.
IOW, the source option already supports a `key=value` style.
so I changed to keep the `key=value` format
=> [ENG-61] change to flavor option format

docs/resources/cli-reference.md, docs/resources/file.md, docs/test-runners/TEMPLATE.md, docs/test-runners/bazel.md, docs/test-runners/behave.md, docs/test-runners/ctest.md, docs/test-runners/cypress.md, docs/test-runners/go-test.md, docs/test-runners/googletest.md, docs/test-runners/gradle.md, docs/test-runners/maven.md, docs/test-runners/minitest.md, docs/test-runners/nose.md, docs/test-runners/robot.md, docs/test-runners/rspec.md
I think we can find a more elegant way to do this in the future, but for now this should help cover off this problem.
FYI @kohsuke and @ninjinkun
=> Always recommend naming a repository in case repo paths change with every build

docs/getting-started.md
Intuitively, I want the link to point to the launchable PyPI page instead of PyPI home page otherwise I feel the link is kind of useless.
=> Update the PyPI link to point to the launchable page

docs/test-runners/nose.md
Documented `--launchable-subset-options` flag on the nose documentation.
=> Update nose documentation

launchable/commands/subset.py, tests/data/minitest/subset_result.json, tests/data/minitest/test/example_test.rb, tests/test_runners/test_minitest.py
- if the users run subset command in miss place, the cli show error message
- fix to trim base path when the user set base option in subset command
=> print warning message when output list is empty

launchable/test_runners/ant.py, tests/data/ant/junitreport/TEST-com.launchable.HelloWorldTest.xml, tests/data/ant/junitreport/TEST-com.launchable.library.CacheTest.xml, tests/data/ant/junitreport/TESTS-TestSuites.xml, tests/data/ant/record_test_result.json, tests/data/ant/src/com/launchable/HelloWorld.java, tests/data/ant/src/com/launchable/HelloWorldTest.java, tests/data/ant/src/com/launchable/library/Cache.java, tests/data/ant/src/com/launchable/library/CacheTest.java, tests/data/ant/subset_result.json, tests/test_runners/test_ant.py
According to [this Ant tutorial](https://ant.apache.org/manual/tutorial-HelloWorldWithAnt.html), Ant (or old Java project?) put test files into an `src` directory instead of `src/test/java/...`. That is why I thought the plugin needs to support root path + glob like `src/**/*Test.java`.
```shell
launchable subset --build 123 ant 'src/**/*Test.java' > check-launchable.txt
ant junit
```
Users need to edit their `build.xml` to import the subset text file like below (complete `build.xml` is in https://github.com/launchableinc/rocket-car-ant).
```xml
<target name="check-launchable">
<available file="launchable-subset.txt" property="launchable"/>
</target>
<target name="junit" depends="jar,check-launchable">
<mkdir dir="${report.dir}"/>
<junit printsummary="yes">
<classpath>
<path …
```
=> Ant support

launchable/commands/subset.py
to avoid operate path as an array
I checked used by https://github.com/launchableinc/examples/tree/master/rspec
```
$ launchable subset --target 50% --build mm rspec spec/
spec/odels/article_spec.rb
spec/odels/comment_spec.rb
spec/equests/articles_spec.rb
spec/equests/comments_spec.rb
```
```
$ launchable subset --target 50% --build mm rspec spec/
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/requests/articles_spec.rb
spec/requests/comments_spec.rb
```
=> [ENG-113] use os.path.relpath

launchable/commands/record/tests.py, launchable/test_runners/bazel.py, tests/cli_test_case.py, tests/commands/record/test_tests.py, tests/test_plugin.py, tests/test_runners/test_ant.py, tests/test_runners/test_bazel.py, tests/test_runners/test_behave.py, tests/test_runners/test_ctest.py, tests/test_runners/test_cypress.py, tests/test_runners/test_go_test.py, tests/test_runners/test_googletest.py, tests/test_runners/test_gradle.py, tests/test_runners/test_maven.py, tests/test_runners/test_minitest.py, tests/test_runners/test_robot.py, tests/test_runners/test_rspec.py
In some environments, the report files have been staying. then the record tests command sends old test results to Launchable.
So we changed to check that timestamp of the report file is newer than the time of record build start at.
=> [ENG-115] to check report file timestamp

launchable/commands/record/tests.py, setup.cfg, tests/commands/record/test_tests.py
the CLI should continue to report the results if the CLI can't parse the time string.
so I add an error handling when parsing the time string.
=> [ENG-115] add error handling to parse the time string

launchable/commands/record/case_event.py
in 3.7, need to use typing_extensions
> Python 3.7 stdlib has an older version of typing.py and won't be updated.
https://github.com/python/typing/issues/707
in 3.8, Literal was added in typing
https://docs.python.org/3/library/typing.html#typing.Literal
but we don't use Literal so I removed
=> remove Literal

launchable/commands/subset.py, tests/data/maven/subset_by_confidence_result.json, tests/test_runners/test_maven.py
I implemented the `confidence` option of the `launchable subset` command
the confidence base subsetting is one of the subsetting types
https://api-docs.mercury.launchableinc.com/#tag/subset
=> [ENG-116] Confidence base subsetting

docs/test-runners/bazel.md
I added document for `--build-event-json` option.
Could you review it?
related PR: https://github.com/launchableinc/cli/pull/215
=> [ENG-115] Add document for build-event-json-file option of the bazel plugin

docs/test-runners/adb.md
I added ADB plugin doc about #226. 
@awilkes We decided to release the first ADB plugin as a pre-release. So, I'd like to ask you about:
* Do we announce this release as "pre-release" in [the release notes](https://github.com/launchableinc/cli/releases)?
* I filled the "Recording test results" section with the link to the Gradle plugin. Please review and revise it.
=> ADB plugin doc

launchable/test_runners/nunit.py, launchable/utils/sax.py, tests/data/nunit/output.xml, tests/data/nunit/record_test_result.json
A customer reported that their NUnit report file didn't parse. Upon
inspection, theirs only had the start-time attribute at the root
element.
I suspect NUnit2 produces that kind of output but not entirely sure the
origin of it. In any case, the robustness feels worthwhile
=> NUnit parsing error fix

launchable/commands/record/tests.py, tests/commands/record/test_tests.py
- If for some reasons we fail to obtain a valid timestamp, we should err
on the side of disabling up-to-date checks, as opposed to not collecting
anything, which is what `now()` was doing.
- Added additional debug & warning messages that situations like this
will be flagged more proactively, or else the user will never notice
what's going on.
See: https://launchableinc.atlassian.net/l/c/AmddErcw
=> Up-to-date check improvement & bug fix

launchable/utils/session.py
We just found out that Jenkins pipeline assigns a new Unix session for every process it launches.
=> Scope a session to a Jenkins build if we are running in one.

launchable/utils/authentication.py, tests/utils/test_authentication.py
I've changed the authentication_headers method and set the `GitHub-Pr-Head-Sha` header only when it exists in the environment. Otherwise, the method sets an empty string to the `GitHub-Pr-Head-Sha` header and that could be confusing to the API.
=> Set GitHub-Pr-Head-Sha header only when it exists

launchable/commands/subset.py
In some environments, charmap codec can't encode character error happened.
so I set character encode when open a file to avoid the error
=> set character encoding format to avoid parse error

launchable/commands/record/tests.py, launchable/utils/http_client.py, launchable/utils/logger.py, tests/utils/test_logger.py
The current default logging level is too high and even warnings and errors do not show up to stdout by default. I believe it is a common practice in CLI that shows logs the level above warning by default. For example, [the Python logging library](https://docs.python.org/ja/3/howto/logging.html) sets the default log level to the warning. 
Also, the `--debug` option contradicts the `--log-level` option and I believe a user should control it by `--log-level` option.
=> Change the default log level to warning

setup.cfg
I got the following error on GitHub Actions when executing launchable cli.
> ImportError: cannot import name 'ichunked' from 'more_itertools' (/usr/lib/python3/dist-packages/more_itertools/__init__.py)
>  -- https://github.com/x-motemen/ghq/runs/2932241995?check_suite_focus=true
I upgraded `more_itertools` and resolved the problem.
I checked and found that the `ichunked` was introduced in version 7.1.0, so we need to specify a dependent version in higher versions.
ref. https://more-itertools.readthedocs.io/en/stable/versions.html#id13
=> fix the dependent version of more_itertools to higher than 7.1.0

launchable/commands/record/tests.py
When I run `pipenv run test tests/commands/test_helper.py` individually, I found the following error. To avoid this circular import error, I modified a relative import to an absolute import according to this [article](https://stackoverflow.com/questions/7336802/how-to-avoid-circular-imports-in-python).
```
ImportError: cannot import name 'find_or_create_session' from partially initialized module 'launchable.commands.helper' (most likely due to a circular import) (/Users/ninjin/src/github.com/launchableinc/cli/launchable/commands/helper.py)
```
I'm going to research which we should use absolute imports or relative imports after merged this PR.
=> Use absolute import to avoid circuler import

docs/resources/cli-reference.md, launchable/commands/record/build.py
One of our customers had trouble running the git submodule command due to their environmental problem. To circumvent the problem, I added a new `--no-submodules` option to the record build command to disable information collection from Git Submodules (and skip running the git submodule command internally).
=> Add no-submodules option to the record build command

launchable/utils/http_client.py, tests/test_runners/test_gradle.py
The same with https://github.com/launchableinc/nose-launchable/pull/44 and change it to retry requests when it fails.
=> Retry when a request failed

launchable/commands/record/commit.py
In our customer's environment, a path for `exe_deploy.jar` contained white space such as `c:\program files\...`. It causes a failure in `launchable record commit` command. To resolve it, I enclose the path with double-quotes.
=> Enclose Jar path including white space with double quotes

launchable/utils/http_client.py, tests/utils/test_http_client.py
Now, it is difficult to check that which test runner is used. This change helps us to resolve it.
=> Contains test runner name to User Agent

docs/resources/integrations/googletest.md
The document is broken because it's not closed.
=> Close the hint style

launchable/commands/record/build.py
When a repository is shallow-cloned, a revision walk is not possible
further than the shallow depth. Add an option to the record build
command to skip the commit collection and let the user upload the commit
data in a separate workflow.
=> Add an option to skip the commit collection

launchable/commands/record/case_event.py, launchable/commands/record/tests.py, launchable/commands/subset.py, launchable/testpath.py, tests/test_testpath.py
Some test runners produce absolute paths. This makes a problem when we make statistical data for tests as those absolute paths can vary per machine or per run.
The CLI has an option to specify a base path to make a relative path from those absolute paths. This change teaches the CLI to guess the base path based on the Git repository root directory.
=> Guess the base path for relativizing test file paths 

Pipfile, launchable/commands/record/build.py, launchable/commands/record/tests.py, launchable/commands/subset.py, setup.cfg, tests/test_runners/test_gradle.py, tests/test_runners/test_minitest.py, tests/test_runners/test_nunit.py
I changed some outputs to understand easily 
```
$ launchable record build --name cli
Processed 22 commits
Launchable recorded build cli to workspace launchableinc/mothership with commits 1 repositories
| .      | .      | 4d6098b73d1f848b2b5f2b3ff6a0cd270c757ed4 |
```
```
$ find -f tests/**/test_*.py | launchable subset --build cli --confidence 80% file  > subset.txt
Launchable created subset 1374 for build cli (test session 300) to workspace launchableinc/cli
|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |           29 | …
```
=> Improve cli outputs

launchable/__main__.py, launchable/commands/inspect/__init__.py, launchable/commands/inspect/subset.py, tests/cli_test_case.py, tests/commands/inspect/test_subset.py
Add `launchable inspect subset` command to check subset result.
e.g) launchable/cli 
```
$ launchable inspect subset --subset-id <subset-id>
|   Order | Test Path                                   | In Subset   |   Estimated duration (sec) |
|---------|---------------------------------------------|-------------|----------------------------|
|       1 | file=tests/test_plugin.py                   | ✔           |                      0.001 |
|       2 | file=tests/test_runners/test_bazel.py       | ✔           |                      0.001 |
|       3 | file=tests/test_runners/test_gradle.py      | ✔           |                      0.001 |
|       4 | file=tests/test_version.py                  | ✔           |                      0.001 |
|       5 | file=tests/utils/test_click.py …
```
=> Add inspect command

launchable/commands/record/build.py
`pipenv run launchable record tests --build 'build-including/slash' go-test report.xml` failed with `404 Client Error`. this cli uses the specified build name as a part of a request path as follows:
```
https://{API_ENDPOINT}/intake/organizations/{ORGANIZATION_NAME}/workspaces/{WORKSPACE_NAME}/builds/{BUILD_NAME}/{SESSION_NAME}
```
When specifying the build name including forward slashes, `GET build` requests fail due to an unexpected build name or session name.
```
$ pipenv run launchable record tests --build 'tw/my-build-name' go-test report.xml
Build tw/my-build-name was not found. Make sure to run `launchable record build --name tw/my-build-name` before
404 Client Error:  for url: https://{API_ENDPOINT}/intake/organizations/{ORGANIZATION_NAME}/workspaces/{WORKSPACE_NAME}/builds/tw/my-b …
```
=> fix: validate build name format not to include forward slash

launchable/test_runners/pytest.py, tests/data/pytest/subset_result.json, tests/test_runners/test_pytest.py
- pytest has changed its default test report format from **xunit1** to **xunit2** since version 6.
-  https://docs.pytest.org/en/latest/deprecations.html#junit-family-default-value-change-to-xunit2
- The **xunit2** format no longer includes file names.
- The **xunit1** format includes the file name.
- It is possible to output in xunit1 format by specifying `junit_family=legacy`.
I chose to generate the class name from the file name so that I wouldn't have to change the format. However, it was not possible to create a complete class name from a file name. So I'm going to change it to file name based.
=> [ENG-315] Change pytest from class base to file name base

launchable/commands/inspect/tests.py, launchable/commands/record/tests.py, launchable/commands/subset.py
SSIA
- subset
```
$ find -f tests/**/test_*.py  | launchable subset --build cli --target 50% file > subset.txt
Launchable created subset 1488 for build cli (test session 358) in workspace example/cli
|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |           17 |                       50 |                0.000283333 |
| Remainder |           17 |                       50 |                0.000283333 |
|           |              |                          |                            |
| Total     |           34 |                      100 |                0.000566667 |
Run `launchable inspect subset --subset-id 1488` to view full subset details
```
- record …
=> inform inspect command

launchable/commands/inspect/__init__.py, launchable/commands/inspect/tests.py, launchable/commands/record/tests.py, launchable/commands/subset.py, tests/cli_test_case.py, tests/commands/inspect/test_tests.py
I implemented `launchable inspect tests --test-session-id <id>` command
<details>
<summary> output of launchable inspect tests in cli </summary>
```
$ launchable inspect tests --test-session-id <id>
| Test Path                                                                                                                                                                                                  |   duration (sec) | Status   | Uploaded At                   |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------|----------|-------------------------------|
| file=tests/utils/test_logger.py#testsuite=tests.utils.test_lo …
```
=> [ENG-308] Inspect tests command

launchable/commands/verify.py
This makes sure that we can get the system information even if there's
an error. The values are quoted by repr. This converts NoneType into a
str and shows non-printing characters if there's any.
=> Print the system information first

docs/resources/integrations/pytest.md
Update pytest document to use `--collect-only` option.
Merge this after releasing https://github.com/launchableinc/cli/pull/307.
=> Update pytest document to use `--collect-only` option.

setup.cfg
[more_itertools](https://more-itertools.readthedocs.io/en/stable/versions.html) dropped python 3.5 support since v8.6.
=> Specify `more_itertools` version lower than v8.6 in Python 3.5

setup.cfg
Since https://github.com/launchableinc/cli/pull/331, I read up on all dependency module's changelogs in `setup.cfg`. As a result, I found `requests` 2.26 and `click` 8.0 dropped Python 3.5. We already specified `~= 7.0` to `click`. So, I specified `requests<2.26` in Python 3.5.
=> Specify `requests` version in Python 3.5

.github/workflows/python-package.yml, tests/cli_test_case.py, tests/test_session.py
A session file that was created in this repo's CI was deleted by tests (by clean_test_session_files method)
Then, two test sessions were created 1) subset command, 2) record test command but it's not intented.
So I create a temp dir  and use it in test to avoid deleting a session file that this repository created in CI.
=> create temp dir and use it for session dir in tests

docs/resources/integrations/ctest.md
Without these, the XML files required for `record tests` are not written.
=> Add required ctest options

launchable/commands/record/build.py, launchable/utils/click.py
When the user uses `--no-commit-collection` option, the cli can't send commit hashes. 
So I add `--commit` option to be able to send repository name and commit hash.
```
$ launchable record build --name build1 --no-commit-collection --commit repoA:hash123456 --commit repoB:hash67890
Warning: Commit collection is turned off. The commit data must be collected separately.
Launchable recorded build build1 to workspace launchableinc/mothership with commits from 3 repositories:
| .      | .      | 6bf701222e2b56a935862a78eb8b40e5a8fcaeb2 |
| repoA  |        | hash123456                               |
| repoB  |        | hash67890                                |
```
=> Add commit option

tests/test_testpath.py
It seems that from a certain Git version the GIT_*_NAME parsing gets
strict and this fails at Git 2.34.1 at least. Use _EMAIL env var for
emails.
=> Use GIT_AUTHOR_EMAIL and GIT_COMMITTER_EMAIL

launchable/__main__.py, launchable/commands/record/build.py, launchable/commands/record/commit.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/split_subset.py, launchable/commands/subset.py, launchable/commands/test_path_writer.py, launchable/utils/http_client.py, launchable/utils/logger.py
To realize it, I Added dry_run mode to LaunchableClient so that it will refrain from making actual requests in case of HTTP methods with side effects. I also changed it so that no request is made inside the jar.
Here is how it works in my environment.
```console
$ launchable --dry-run --log-level=info record build --name "test-$(date)" --source .
AUDIT:launchable:(DRY RUN) send request method:get path: https://api.mercury.launchableinc.com/intake/organizations/{maskxxx}/workspaces/{maskxxx}/commits/latest
AUDIT:launchable:(DRY RUN) send request method:post path:https://api.mercury.launchableinc.com/intake/organizations/{maskxxx}/workspaces/{maskxxx}/commits/collect headers:{"Content-Type":"application/json","Content-Encoding":"gzip"} args:{
"commits" : [ {
"id" : 0,
"workspaceId" : 0, …
```
=> Add the dry-run option globally

Pipfile, README.md
Apparently, one of those dev dependencies pulls latest more_itertools,
which conflicts with the main app's dependency. Pin the version in the
dev dependencies as well.
=> Add a constraint on more_itertools in Pipfile

launchable/utils/http_client.py, setup.cfg, tests/test_runners/test_jest.py, tests/test_runners/test_minitest.py, tests/test_runners/test_nunit.py
To suppress DeprecationWarning.
I explicitly specify the version of urllib3 that the request package depends on as 1.26 or later. This is the version in which `allowed_methods` was introduced.
- https://github.com/urllib3/urllib3/blob/1dd0613b610df1269dbc11e9780b0fe7debaff3c/CHANGES.rst#1260-2020-11-10
- https://github.com/urllib3/urllib3/pull/2000
Also, the requests library has been updated to support urllib3 v1.26 since version 2.25, so I specify that as well.
https://github.com/psf/requests/blob/main/HISTORY.md#2250-2020-11-11
These changes meet our version requirements to support python 3.5.
=> use allowed_method option instead of method_whitelist

docs/resources/cli-reference.md, launchable/commands/record/commit.py, launchable/utils/ingester_image.py
It may be that no one uses the docker option. And the docker image is old, not following up with the recent new features of the cli such as audit and dry-run.
So, how about deleting it?
I leave the option as a hidden flag for now. I plan to remove it completely in the future.
=> drop --executable docker option

docs/resources/cli-reference.md
I implemented it at https://github.com/launchableinc/cli/pull/344, but I forgot to add the document.
=> add documentation for --dry-run

README.md
- sorry for a silly mistake. I had to escape `>`
=> escape > in markdown

launchable/commands/helper.py, launchable/utils/session.py
We want to show this message when the user can't read a build name that is saved.
> "Have you run `launchable record build`?\nIf not, please do. If it was run elsewhere/earlier, please use the --session option",
However, now this message is printed first so I changed validation orderes
> Given build name ({}) is different from when you ran `launchable record build --name {}`.\nMake sure to run `launchable record build --name {}` before."
=> fix error message order

launchable/utils/session.py, tests/test_session.py
Before this change, the cli requires to run `launchable record build` before executing `launchable record session`.
But, it is unintended behavior so I removed validation logic.
=> rm validation

launchable/commands/record/build.py, launchable/commands/record/session.py, setup.cfg, tests/cli_test_case.py
- updated click version for >=python3.6 to use >=click8.0
- since click>=8.0 turns tuple to string in returning, as is in TODO, added some workarounds  https://github.com/launchableinc/cli/pull/363/commits/5171c1c362042eabd1dd44ab2c2d6c608a64a1c8
TODO:
- handle extraction of flavor tuple to dict in better way for >=click8.0 that returns tuple of tuples as tuple of str
E.G. 
<click8.0: 
`launchable record session --build aaa --flavor os=ubuntu --flavor python=3.5` is parsed as build=aaa, flavor=(("os", "ubuntu"), ("python", "3.5"))
>=click8.0: 
`launchable record session --build aaa --flavor os=ubuntu --flavor python=3.8` is parsed as build=aaa, flavor=("('os', 'ubuntu')", "('python', '3.8')")
=> updated click version for >=python3.6

launchable/test_runners/cucumber.py, tests/data/cucumber/record_test_json_result.json, tests/data/cucumber/report/result.json, tests/test_runners/test_cucumber.py
I supported a JSON report format file in the cucumber plugin.
e.g) 
```sh
launchable record tests cucumber --json ./report/**/*.json
```
There are some different formats between XML formant and JSON format. So, JSON's report data that cli sends to Launchable is a little different from using XML formats. 
But cucumber will use file names to subsetting so there is no problem.
___ 
If the user set not JSON file, cli shows an error message like this
```
$ launchable record test cucumber --json ./report/TEST-features-foo-bar.xml
...
raise Exception(exceptions)
Exception: [Exception('Failed to process a report file: ./report/TEST-features-foo-bar.xml', Exception("Can't read JSON format report file ./report/TEST-features-foo-bar.xml. Make sure to confirm report file."))]
```
And if the user set …
=> Add --json option to cucumber plugin

launchable/commands/record/build.py, tests/commands/record/test_build.py
Found in https://github.com/launchableinc/cli/pull/366. It should check
if the item is a str instead of commits itself is a str. Added a test,
but it indicates the cli is calling git command even if --commit is
specified, this should be fixed in the forementioned PR.
=> Check if commits item is a str

launchable/commands/record/build.py, tests/commands/record/test_build.py
* If --no-commit-collection is *not* specified, it runs git commands to
detect HEAD and submodules HEADs. It sends the commit data to the
server.
* If --no-commit-collection is specified, but --commits is *not*
specified, it runs git commands to detect HEAD and submodule HEADs. It
won't send the commit history. This git call is necessary in order to
get the commits that are associated with the build.
* If --no-commit-collection is specified and --commits is specified, it
won't run git commands at all.
=> Do not run git command when --commits is specified

launchable/commands/inspect/subset.py, launchable/commands/inspect/tests.py, launchable/commands/record/build.py, launchable/commands/record/commit.py, launchable/commands/record/session.py, launchable/test_runners/bazel.py, launchable/test_runners/raw.py, launchable/utils/http_client.py
- use sys.exit() instead of exit() in Python program to exit.
=> fix to use sys.exit

launchable/test_runners/nunit.py, tests/data/nunit/record_test_result.json, tests/data/nunit/subset_result.json
I changed to replace `TestFixture` to `TestSuite`. Because  I found out Nunit produces a different XML attributes report file between with `--explore` option and without it.
=> Fix Nunit plugin

docs/resources/integrations/ctest.md
--output-regex-files and --output-regex-files-dir are the options under
ctest, not at the root level.
=> Fix the ctest command example

launchable/test_runners/pytest.py, tests/data/pytest/subset_result.json, tests/data/pytest/tests/fooo/filenameonly_test.py, tests/test_runners/test_pytest.py
In python, we can write functions directly under the file.
In this case, the behavior of parsing TestPath becomes strange.
=> rescue file::testcase case

tests/commands/record/test_commit.py
Now, we send a request to production in the record commit test. But it's not good.
e.g) https://github.com/launchableinc/cli/runs/5323115390?check_suite_focus=true#step:10:92
I changed to use a mock server to avoid request production directly
=> Improve record commit test

docs/resources/troubleshooting.md
If DNS doesn't resolve during `record build` we get this:
```
2022-03-08_09:53:25  parallel: timeit run_launchable:	Exception in thread "main" java.net.UnknownHostException: api.mercury.launchableinc.com: No address associated with hostname
2022-03-08_09:53:25  parallel: timeit run_launchable:		at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2022-03-08_09:53:25  parallel: timeit run_launchable:		at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
2022-03-08_09:53:25  parallel: timeit run_launchable:		at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
2022-03-08_09:53:25  parallel: timeit run_launchable:		at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) …
```
=> Added another reported failure mode

launchable/test_runners/nunit.py
Some folks invoke `nunit --explore` separately for different DLLs yet we still would like to make one subset call to select meaningful tests across all such DLLs.
=> Support multiple XML files

tests/commands/test_api_error.py
`record commit` command exec `exe.jar`. However, we hadn't mocked and checked it.
So, I changed to check it.
=> Add error case

.github/workflows/python-package.yml, .github/workflows/python-publish.yml, .github/workflows/test-python-publish.yml, setup.cfg, setup.py
- change PyPI authentication to API token
- use Test PyPI for test publish and PyPI for official one
- update Github actions for PyPI publish
- github action: https://github.com/marketplace/actions/pypi-publish
- usage with build and publish: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> change pypi publish to API token auth

setup.cfg
Click dropped Python 3.6 support since 8.1 and we need to restrict the
version for it. Since we also need to support Python 3.5, which is not
supported by Click since 8.0, the version specifier is split into three.
=> Narrow down the click version for Python 3.6

.github/workflows/e2e.yml, .github/workflows/python-package.yml
- This PR is to add support for Python3.10.x.
- We already have cli support for Python 3.5.x to 3.9.x. Python3.9.13 is released recently as the last version for 3.9 series. Since Python 3.10.x becomes the latest series to be updated, it will be mandatory to support Python 3.10 for customers updating to the latest Python.
[Python Release Python 3.9.13](https://www.python.org/downloads/release/python-3913/) 
- Python3.11 already exists, but it is unnecessary to support until it becomes main stream.
[What’s New In Python 3.11 — Python 3.11.0b1 documentation](https://docs.python.org/3.11/whatsnew/3.11.html)
=> add Python3.10

launchable/test_runners/maven.py, tests/test_runners/test_maven.py
A class list file that was produced by `mvn test-compile` is included inner classes. But we support only top class so I fixed to ignore inner class.
this is example that `mvn test-compile` will be produced
```
com/hoge/Fuga.class
com/hoge/Fuga$InnerClassName.class
```
=> Ignore inner class for --test-compile-create-file option

docs/resources/cli-reference.md
Fix the broken link on the [cli-reference page](https://docs.launchableinc.com/resources/cli-reference).
=> docs: fix broken link to the integration page

docs/resources/integrations/pytest.md
At https://github.com/launchableinc/pytest-launchable/pull/15, I renamed the option names to hyphenated. That is why I modified the option name in doc.
=> Change an option name in the doc

launchable/commands/record/commit.py
Al noticed that we no longer seem to be reporting the # of commits collected:
```
awilkes@MacBook-Pro cli-demo % launchable record build --name 20220615-2 --source src=cli
Launchable recorded build 20220615-2 to workspace launchableinc/awilkes with commits from 1 repository:
| src    | cli    | ec205499a358f3b9b7a06a182cc819c5536b631e |
awilkes@MacBook-Pro cli-demo % launchable record commit --source cli
awilkes@MacBook-Pro cli-demo %
```
I looked into this and realized that PR #375 introduecd this change. Judging from https://github.com/launchableinc/cli/pull/375, this is probably unintended.
The change makes sure stdout/stderr of the commit collection process is …
=> Don't swallow the output message from commit collection

launchable/test_runners/maven.py, launchable/utils/glob.py, tests/test_runners/test_maven.py, tests/utils/test_glob.py
Maven Surefire has a mechanism to not only recursively scan directories to find tests but also include/exclude subset of the files as valid tests.
Emulate this behavior to collectly list up tests that should be selected. Since these are configurable parameters in our CLI as well, but I'm kicking that can down the road until it's needed. Especially given that the long term future of the Maven support would have to be in-process.
=> Honor default test inclusion/exclusion with Maven

launchable/commands/record/commit.py, tests/commands/record/test_commit.py
Prior to this change, the proxy config is concatenated as one string
(e.g. ['java', '-Dhttps.proxyHost=something -Dhttps.proxyPort=80']).
This must be ['java', '-Dhttps.proxyHost=something',
'-Dhttps.proxyPort=80'].
The formatting is automatically done by pre-commit.
=> Properly construct HTTPS proxy array

launchable/commands/record/tests.py, tests/cli_test_case.py, tests/test_runners/test_cypress.py, tests/test_runners/test_go_test.py
Slack notification feature is already closed beta ref: https://docs.launchableinc.com/features/test-notifications-via-slack
So, I changed to enable this feature by default.
=> Enable slack notification default

launchable/commands/helper.py, launchable/commands/record/session.py, launchable/commands/subset.py, tests/commands/record/test_session.py
Add new option `--observation`.
If the user uses this option, Launchable will show details information for the subset and the record test results.
=> Add observation mode

launchable/commands/record/session.py, launchable/commands/split_subset.py, launchable/commands/subset.py, tests/commands/record/test_session.py, tests/commands/test_split_subset.py, tests/commands/test_subset.py
At first, we planned to receive a merged subset result (subset + rests) from Launchable. However, if we did so, output summary data will be changed.
So I changed to merge at the cli side.
I made another PR https://github.com/launchableinc/cli/pull/437 before, however, we need to release faster than zero input subsetting mode. So, I made a new PR.
=> Implement observation mode output

launchable/commands/subset.py, tests/commands/test_subset.py, tests/data/adb/subset_result.json, tests/data/ant/subset_result.json, tests/data/bazel/subset_result.json, tests/data/behave/subset_result.json, tests/data/ctest/subset_result.json, tests/data/cypress/subset_result.json, tests/data/go_test/subset_result.json, tests/data/googletest/subset_result.json, tests/data/jest/subset_result.json, tests/data/maven/createdFile_1.lst, tests/data/maven/createdFile_2.lst, tests/data/maven/subset_by_absolute_time_result.json, tests/data/maven/subset_by_confidence_result.json, tests/data/maven/subset_from_file_result.json, tests/data/maven/subset_result.json, tests/data/nunit/subset_result.json, tests/data/pytest/subset_result.json, tests/data/robot/subset_result.json, tests/test_runners/test_raw.py
I added two options 
- `--output-exclusion-rules`
- `--get-tests-from-previous-full-runs`
When the `--output-exclusion-rules` option enabled, the cli will switch the subset result and the rest result for excluding option
e.g)
```sh
launchable subset --target 30% --output-exclusion-rules src/test/** > exclude.txt
mvn test -Dsurefire.excludesFile=exclude.txt
```
The `get-tests-from-previous-full-runs` option is new feature of subset. The user can execute a subset request without subset test lists, after reporting test results sometimes.
=> Add options for zero input subsetting

launchable/commands/record/session.py, launchable/utils/ci_provider.py, tests/commands/record/test_session.py
The CLI captures job links from CI providers in the `test sessions` command to show the links on the web app. It supports the following providers:
* Jenkins
* Github Action
* CircleCI 
* It doesn't exist in the original plan, but I added it because it's easy to add.
=> Capture job links

docs/resources/integrations/raw.md
I found the following broken link and section (no link) and want to fix for what we expect.
* Fix markdown syntax for `#subsetting-hierarchy`
* Make the "Subsetting hierarchy" section linkable
=> doc: fix link to Subsetting hierarchy

launchable/commands/record/commit.py, launchable/utils/java.py
Failure mode:
```
Exec: /cygdrive/c/[reducted]/.venv/bin/launchable record build --name XYZ --source ABC=/cygdrive/c/abc/def
: Command '['java', '-jar', '/cygdrive/c/[reducted]/git-utils/.venv/lib/python3.8/site-packages/launchable/jar/exe_deploy.jar', 'ingest:commit', '-endpoint', 'https://api.mercury.launchableinc.com/intake/', '-max-days', '30', '-scrub-pii', '/cygdrive/c/abc/def']' returned non-zero exit status 1.
: Launchable recorded build XYZ to workspace abc/def with commits from 1 repository:
:
: | Name          | Path                        | HEAD Commit                              |
: |---------------|-----------------------------|------------------------------------------|
<< reducted >>
: Error: Unable to access jarfile …
```
=> Cygwin support

docs/resources/integrations/maven.md
Typical maven projects are multi-module, and enumerating modules is not practical. At least one customer attempted to use '**' but unable to realize that their shell is expanding it, not our CLI, and got stuck.
Switching to a more realistic example that's ready for copy/paste, and calling out an attention to the use of quotes to preserve GLOB.
=> Updated based on a customer support request.

launchable/commands/record/commit.py, launchable/utils/commit_ingester.py, launchable/utils/git_log_parser.py, tests/data/git_log_ingest/sample.out, tests/utils/test_git_log_parser.py
This implements --import-git-log-output option. In some cases, it's hard
to access the git repository from the machine that connects to the
Internet. This makes a workaround that a user can create a file based on
a Git log command (shown in the doc comment), transfer that to the
machine with the Internet connection, and run a commit ingestion.
Tested with one of the demo workspaces.
=> Add a git-log parser

launchable/commands/split_subset.py
- Renamed variable `bin` in Python to `bin_target` since `bin` is a reserved word in Python.
- https://docs.python.org/ja/3/library/functions.html#bin
=> rename bin variable name to bin_target to avoid using reserved word bin

launchable/test_runners/raw.py, tests/test_runners/test_raw.py
The parser used for raw profile test runner does not parse and create testPath field for `record tests` payload as our expected format. Currently the format of the `testPath`  field is `string` but it must be `Array<TestPathComponent>`.
This causes the following 500 error.
```
$ pipenv run launchable record tests --session SOMETHING raw ~/Downloads/downloadHaSR1065559/TEST-report.json
File "/Users/takayuki-watanabe/src/github.com/launchableinc/cli/launchable/commands/record/tests.py", line 324, in run
send(p)
File "/Users/takayuki-watanabe/src/github.com/launchableinc/cli/launchable/commands/record/tests.py", line 292, in send
res.raise_for_status()
File "/Users/takayuki-watanabe/.local/share/virtualenvs/cli-f4jrwhCf/lib/python3.10/site-packages/requests/ …
```
=> fix invalid testPath format for raw profile testRunner

.github/workflows/python-package.yml
Reverts launchableinc/cli#444.
We have enough production data that this change can be reverted.
=> Revert "Temporarily enable observation mode to generate some prod data"

launchable/commands/helper.py, tests/cli_test_case.py, tests/commands/test_helper.py
When executing a `launchable subset` command with a session issued by the `launchable record session` command and want to enable observation mode, the user needs to `—observation` option to the `launchable record session` command.
However, sometimes the option is set to the `launchable subset` command, and observation mode isn’t enabled.
So, added a warning message when it happened.
```sh
$ $ launchable record build --name observation-mode
$ launchable record session --build observation-mode > session.txt
$ find tests/**/test_*.py | launchable subset --session $(cat session.txt) --target 30% --observation file > subset.txt
Warning: you set --observation option this command but you need to set it `launchable record session` command # added
Your model is currently in training
Launchable …
```
=> Add warning when the user set --observation option to subset command not record session command

launchable/commands/split_subset.py, launchable/commands/test_path_writer.py, launchable/test_runners/go_test.py, launchable/test_runners/gradle.py, launchable/test_runners/launchable.py, tests/cli_test_case.py, tests/commands/test_split_subset.py, tests/test_runners/test_go_test.py, tests/test_runners/test_gradle.py, tests/test_runners/test_raw.py
- Add `same bin` support for split subset. It is aimed to support grouping some tests that must not be run parallel simultaneously.
- The `same bin` is specified in a text file, with a test per line, and passed with `--same-bin` option.
- Tests specified to the same bin will be packed to the same bin in the split.
- It is possible to specify multiple `same bins`.
- For example, we have 9 tests, and we do not like DB0Test and DB1Test to run parallel, and File0Test and File1Test to run parallel as well.
```sh
$ launchable inspect tests --test-session-id 6
| Test Path                             |   Duration (sec) | Status   | Uploaded At                 |
|---------------------------------------|------------------|----------|-----------------------------|
| …
```
=> add same bin option to subset split

launchable/__main__.py, launchable/commands/record/session.py, launchable/commands/stats.py, launchable/commands/stats/__init__.py, launchable/commands/stats/test_sessions.py, launchable/utils/flavor.py, launchable/utils/http_client.py
With this change, we can get the stats of test sessions via the API, which can be obtained with the stats subcommand.
There is also a function to filter by number of days and flavor, which is useful for predicting test times before running tests.
```console
$ curl -H "Content-Type: application/json" -H "Authorization: Bearer $LAUNCHABLE_TOKEN" https://api.mercury.launchableinc.com/intake/organizations/OOO/workspaces/WWW/stats/test-sessions'?flavor=os=ubuntu-latest'
{"averageDurationSeconds":0.007610803807083564,"count":158,"days":7}
```
```console
$ launchable stats test-sessions --flavor=os=windows-latest
{"averageDurationSeconds":0.007610803807083564,"count":158,"days":7}
```
=> add `stats test-sessions` subcommand

docs/features/predictive-test-selection/requesting-and-running-a-subset-of-tests/replacing-static-parallel-suites-with-a-dynamic-parallel-subset.md, docs/resources/cli-reference.md
- Add documentation for `--same-bin` option on `split-subset`.
- https://github.com/launchableinc/cli/pull/470
=> add same bin option document

launchable/__main__.py, tests/test_testpath.py
- Fix git submodel test for workaround to support git-shell update happened 18th October, 2022.
- https://bugs.launchpad.net/ubuntu/+source/git/+bug/1993586
- Our github actions started to fail due to git-shell update: https://github.com/launchableinc/cli/actions/runs/3292983667/jobs/5429303370
- Apply format and isort.
=> fix git submodule test to support git-shell update

launchable/commands/subset.py, launchable/test_runners/gradle.py, tests/commands/test_api_error.py, tests/commands/test_subset.py, tests/test_runners/test_raw.py
⚠️ **This PR includes breaking change.** ⚠️ 
Before this change, when the rest response is empty we fill a test path to the rest output not to suspend the user pipeline that depends on the rest output. However, the behavior breaks the policy that the subset and the rest should be a pair.
So, I fixed it. And, I summarized the subset and the rest output rules.
e.g) 
Assume there are test_paths, `file=aaa.py`, `file=bbbb.py`, `file=111.py`, and `file=222.py`, also `file=aaa.py` and `file=bbb.py` are included in the subset, `file=111.py` and `file=222.py` are included the rest.
| command | subset | rest |
|:---:|:---:|:---:|
| `launchable subset --target 50% file` | `file=aaa.py`, `file=bbb.py`|  `file=111.py`, `file=222.py`
| `launchable subset --observation --target 50% file` | …
=> fix subset and rest output to be pair

docs/SUMMARY.md
It seems that GitBook won't render a page otherwise.
=> Add the migration page to the SUMMARY

.github/workflows/e2e.yml, .github/workflows/python-package.yml, .github/workflows/python-publish.yml
- Update setup-python to v4. https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-python
- Fix Ubuntu-latest to ubuntu-20.04 since the current `ubuntu-latest` is `ubuntu-22.04` which does not support Python3.5 and 3.6.
- See below for Python version and OS support.
- https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
=> update setup python version to v4; use Ubuntu-20.04 for Github Actions

launchable/commands/record/tests.py, tests/commands/record/test_tests.py, tests/data/ant/record_test_result.json, tests/data/bazel/record_test_result.json, tests/data/bazel/record_test_with_build_event_json_result.json, tests/data/bazel/record_test_with_multiple_build_event_json_result.json, tests/data/behave/record_test_result.json, tests/data/ctest/record_test_result.json, tests/data/cucumber/record_test_json_result.json, tests/data/cucumber/record_test_result.json, tests/data/cypress/record_test_result.json, tests/data/go_test/record_test_result.json, tests/data/googletest/fail/record_test_result.json, tests/data/googletest/record_test_result.json, tests/data/gradle/recursion/expected.json, tests/data/jest/record_test_result.json, tests/data/maven/record_test_result.json, tests/data/minitest/record_test_result.json, tests/data/nunit/record_test_result.json, tests/data/pytest/record_test_result.json, tests/data/robot/record_test_result.json, tests/data/rspec/record_test_result.json, tests/test_runners/test_raw.py
Provide a new option as `group` for `launchable record tests` command.
When reports test results, can set the group name using a new option
e.g)
```
$ launchable record tests --group unit-test ./test-reports/unit-test.xml
$ launchable record tests --group e2e ./test-reports/e2e.xml
```
=> add group option

launchable/commands/subset.py, launchable/test_runners/raw.py, tests/test_runners/test_raw.py
Now the raw plugin isn't supported [Zero Input Subsetting](https://docs.launchableinc.com/resources/integrations/gradle#using-zero-input-subsetting).
So, I updated the raw plugin to support Zero Input Subsetting.
e.g)
```
$ launchable subset --target 30% --get-tests-from-previous-sessions -rest rest.txt > subset.txt
$ pytest $(cat rest.txt | grep file= | awk -F# '{print $1}' |  awk -F= '{print $2}' | sort | uniq | xargs -I% echo '--ignore %' | tr '\n' ' ')
```
=> Support zero input subset for raw profile

Pipfile
This is used in the script, but it was not specified in the dependency.
=> Add isort as the dev dependency

.github/workflows/python-package.yml, Pipfile
- Remove lint-warn from GitHub Actions because it is too much.
- Add F401 to ignore in lint since it does not support commented type hinting in Python>=3.7.
=> remove lint-warn from github actions

docs/resources/integrations/maven.md
A recent customer troubleshooting suggests Maven doesn't handle relative path here very well. Instead of interpreting it against the current directory, it interprets it against the module top level directory.
=> Don't pass a relative path

launchable/commands/split_subset.py, launchable/test_runners/gradle.py, tests/cli_test_case.py, tests/commands/test_split_subset.py
Add `--split-by-groups` option to the `split-subset` command
e.g)
```sh
$ launchable record tests --group e2e ./e2e-test-result.xml
$ find ./tests/**/test_*.py  | launchable subset --split --target 40% file > subset_id.txt
$ launchable split-subset --subset-id $(cat subset-id.txt) --split-by-groups file
$ ls -l 
rest-e2e.txt
rest-nogroup.txt
subset-e2e.txt 
subset-groups.txt
subset-nogroup.txt
```
=> Split subset by group

docs/resources/integrations/gradle+testng.md, docs/resources/integrations/maven.md
Documenting how to use Zero Input Subset with TestNG, which impacts both Maven & Gradle.
I created a separate section in Maven to discuss various complications, as opposed to duplicating this twice. Probably a matter of taste, but I made this change based on my thinking that there will be more complications to be added in the future.
=> zero input subset + TestNG support documentation

launchable/commands/record/build.py, tests/commands/record/test_build.py
We don't allow to use '/' for the build name. Sometimes encoded '/' (= %2F) is set to a build name, even if '/' is encoded we don't allow it. So, I added a validation for it.
=> add new validation for build name

Pipfile, launchable/commands/subset.py, launchable/test_runners/maven.py, tests/commands/test_subset.py
I realized some users faced some integration issues, so I edited that easy to notice the cause of issues.
1. If subset candidates are empty and isn't set `--get-tests-from-previous-sessions` option, it's usually integration miss. So, I changed it to an error.
2. In the maven profile, when they set `--test-compile-created-file` and source_roots both, source_roots will be ignored so I updated to show the warning message.
3. Even if `--test-compile-created-file` is set but the file is empty, to show a warning message. 
Also, I fixed some minor changes
=> Add some validations

launchable/commands/record/build.py, launchable/commands/record/session.py
- Reject taking `%25` for build name that may be potentially malicious string.
=> reject %25

launchable/commands/inspect/subset.py, launchable/commands/inspect/tests.py, launchable/commands/record/tests.py, launchable/commands/subset.py, tests/commands/inspect/test_subset.py, tests/commands/inspect/test_tests.py
Estimated duration of "3.33333e-05" is silly. Our valid value range is far limited, and the precision at those small numbers are illusions.
Better to use a fixed point precision. Also limit the number of precision digits. There's enough measurement margin errors, so added digits do not add any real value.
Briefly I was looking to print "3" as "3", not "3.00" but I don't think there's any predefined formatter that does it.
See: https://docs.python.org/3/library/string.html#format-specification-mini-language
=> [WA-77] format with fixed point notation

.github/workflows/python-package.yml, launchable/commands/helper.py, launchable/commands/record/build.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/stats/test_sessions.py, launchable/commands/subset.py, launchable/utils/key_value_type.py, launchable/utils/link.py, tests/commands/record/test_build.py, tests/commands/record/test_session.py, tests/utils/test_key_value_type.py, tests/utils/test_link.py
Add `--link` option to the `launchable record` command and `launchable record session` command. Also, `launchable subset` command and `launchable record tests` command support a link option to pass links value to the `launchable record session` command internally too.
e.g)
```sh
$ launchable record build --name test --link build-url=https://example.launchable.com/job/1 
$ launchable record build --name test --link commit=https://github.com/owner/repo/commits/123abc456
```
Also, if these values (ref: https://github.com/launchableinc/cli/pull/529/files#diff-280a9bc4f9d9c38c29d666a70adf8c4e216a1abb22f548b3a011f9ac00b6bf10R4-R53) are set in the CI environment, the cli sets custom link data automatically.
=> Support link option

launchable/test_runners/perl.py, tests/data/perl/record_test_result.json, tests/data/perl/report.xml, tests/test_runners/test_perl.py
- Add Perl profile to support Perl test.
- The Perl profile is made to take a Junit report produced by [TAP::Harness::JUnit](https://metacpan.org/pod/TAP::Harness::JUnit) with environment variable of `JUNIT_NAME_MANGLE=none`. Otherwise, Launchable cannot support Perl test since the report produced may not contain test file path or duration.
=> add perl profile

launchable/commands/record/session.py, launchable/commands/record/tests.py, tests/cli_test_case.py, tests/commands/record/test_session.py
I supported `--session-name` option to `record session` and `record tests` commands.
Previously, the user needed to pass a test-session-id 
to other machines. The user doesn’t need to pass it if using a `—session-name` option.
```
$  launchable record build --name with-session-name
Launchable recorded 22 commits from repository /Users/yabuki-ryosuke/src/github.com/launchableinc/cli
Launchable recorded build with-session-name to workspace example/test with commits from 1 repository:
| .      | .      | 14c0b210c606bf9a4744167064d282318142511d |
$ launchable record session --build with-session-name --session-name example-name …
```
=> Support --session-name option to `record session` and `record tests` commands

launchable/test_runners/launchable.py
reading file object as a generator returns NL at the end of each line.
See: https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects
=> Fixed a bug in handling arguments from stdin/file

launchable/commands/record/session.py
The output of `launchable record session` is expected to be passed in to `--session` in later commands, and the examples in the documentation suggest that this output should be piped to a file and read back in. This output includes a newline character, which makes working with it annoying: you need to ensure your shell removes the newline with proper quoting. By removing the newline, we make this easier to work with. For example, it can be read in by a Jenkins `readFile` Pipeline step and then passed through to a shell step without quoting.
=> Do not print a newline in `launchable record session`

launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py
We shipped these options as hidden options at first for a safe landing.
But we could confirm it works well, so I changed them from hidden to the public.
=> Change these options to public

launchable/test_runners/cts.py, tests/data/cts/record_test_result.json, tests/data/cts/subset_result.json, tests/data/cts/test_result.xml, tests/test_runners/test_cts.py
I made a new plugin for Compatibility Test Suite (cts)
https://source.android.com/docs/compatibility
```sh
$ launchable record build --name <NAME>
$ launchable record session --build <NAME> > session.txt
$ launchable record tests --session $(cat session.txt) cts android-cts/results/2023.04.03.02.01.00/test_result.xml
Launchable recorded tests for build 1680844815 (test session 12345) to workspace example/test from 1 files:
|   Files found |   Tests found |   Tests passed |   Tests failed |   Total duration (min) |
|---------------|---------------|----------------|----------------|------------------------|
|             1 |           766 |            481 |            281 |                  12.74 |
```
Launchable supports `class` level subset. However, `cts` command cannot list the target …
=> Support Compatibility Test Suite (cts) profile

launchable/commands/record/case_event.py, launchable/test_runners/pytest.py, tests/data/ant/record_test_result.json, tests/data/behave/record_test_result.json, tests/data/ctest/record_test_result.json, tests/data/cucumber/record_test_result.json, tests/data/googletest/fail/record_test_result.json, tests/data/prove/record_test_result.json, tests/data/pytest/record_test_result.json, tests/data/pytest/record_test_result_json.json, tests/data/robot/record_test_result.json, tests/test_runners/test_pytest.py
We had failed to collect stdout and stderr.
So, I checked the test report formats and fixed the codes.
=> Add stdout/stderr method to parse messages

launchable/test_runners/nunit.py
Our nunit plugin hadn't checked the `Skipped` status. 
So, I fixed it to check it.
=> fix to check skip status

launchable/utils/commit_ingester.py
When we collect git commit logs use by exec.jar, then the status will be `MODIFY`. So, I changed the status to align it when the user collecting using the  `launchable record commit` with `--import-git-log-output` option
https://javadoc.io/doc/org.eclipse.jgit/org.eclipse.jgit/5.13.1.202206130422-r/index.html
=> change git status name to allign jgit.diff.DiffEntity.ChangeType

launchable/test_runners/dotnet.py, launchable/test_runners/nunit.py, tests/data/dotnet/record_test_result.json, tests/data/dotnet/test-result.xml, tests/test_runners/test_dotnet.py
```
$ launchable record tests dotnet **/*.xml
$ launchable subset --target 25% --get-tests-from-previous-sessions --output-exclusion-rules dotnet > subset.txt
$ cat subset.txt FullyQualifiedName!=rocket_car_dotnet.ExampleTest.TestAdd&FullyQualifiedName!=rocket_car_dotnet.ExampleTest.TestSub&FullyQualifiedName!=rocket_car_dotnet.ExampleTest.TestDiv
$ dotnet test --filter $(cat subset.txt)
```
We collect NUnit test reports like below
```
Assembly=rocket-car-dotnet.dll#TestSuite=rocket_car_dotnet#TestSuite=ExampleTest#TestCase=TestSub
Assembly=rocket-car-dotnet.dll#TestSuite=rocket_car_dotnet#TestSuite=ExampleTest#TestCase=TestMul
Assembly=rocket-car-dotnet.dll#TestSuite=rocket_car_dotnet#TestSuite=ExampleTest#TestCase=TestDiv
Assembly=rocket-car-dotnet.dll#TestSuite=rocket_car_dotnet#TestSui …
```
=> Supports dotnet profile

setup.cfg
WMI is built on top of COM, and we suspect this is causing CoInitializeEx error on Windows nanoserver docker image:
```
python.exe -m launchable --version
pythoncom error: CoInitializeEx failed (0x80004001)
pythoncom error: OLE initialization failed! (0x80004005)
launchable-cli, version 1.63.0
```
=> Removing WMI dependency.

launchable/commands/split_subset.py, launchable/test_runners/dotnet.py, tests/commands/test_split_subset.py, tests/test_runners/test_dotnet.py, tests/test_runners/test_minitest.py
* Add `--output-exclusion-rules` support to split-subset
* Allow split-subset to output empty rest files (like regular subset)
* Add split-subset support to dotnet profile
=> Add --output-exclusion-rules support to split-subset

launchable/commands/record/build.py, tests/commands/record/test_build.py
Update to collect git branch names.
However, this method cannot collect the correct branch name in some environments. 
So, I commented it, and I'll fix it another PR
e.g) GitHub Actions
result at local 
on GithubAction
=> collect branch name

launchable/commands/record/build.py, tests/commands/record/test_build.py
We used `git rev-parse --abbrev-ref HEAD` to collect a git branch name. However, in detached HEAD case, this command couldn't get a collect branch name and got `HEAD`.  e.g) https://stackoverflow.com/questions/6059336/how-to-find-the-current-git-branch-in-detached-head-state
So, we changed to use environment variables that each CI provider provides and `git show-ref | grep '^'$(git rev-parse HEAD)`
=> Fix way of collecting git branch names

Pipfile
Currently, python lint fails on the main branch such as https://github.com/launchableinc/cli/actions/runs/5528890710/jobs/10086219577. This PR fixes it
=> Specify the version of importlib-metadata

launchable/commands/record/commit.py
Currently, we send one commit which has no parents when the repository is a shallow clone. However, we can't collect all commits data in this case. Thus, we need to ask users to use full clone or disable commit collection by --no-commit-collection option. I added this feature in this PR.
```shell
$ /Users/ono-max/.local/share/virtualenvs/cli-o7XEfK99/bin/launchable --log-level=audit record build --name "testbuild" --max-days 90
Can't collect all commits from /Users/ono-max/workspace/example since it is the shallow repository. Please use full clone or disable commit collection by --no-commit-collection option.
```
=> Validate if the repository uses shallow clones

launchable/commands/record/build.py, tests/commands/record/test_build.py
I realized this sub process failed with `[Errno2] No such file or directory` message. 
We need to set `shell=True` property to fix it ref: https://stackoverflow.com/questions/18962785/oserror-errno-2-no-such-file-or-directory-while-using-python-subprocess-wit
```
$ launchable record build --name investigate-sub-process
Launchable recorded 2 commits from repository /Users/yabuki-ryosuke/src/github.com/launchableinc/cli
[Errno 2] No such file or directory: "git show-ref | grep '^'$(git rev-parse HEAD)"
Launchable recorded build investigate-sub-process to workspace konboi/test with commits from 1 repository:
| .      | .      | 9137f2a04b70d0cb1647f10495e55cec7317764e …
```
=> Fix to pass stdout to next command

launchable/test_runners/dotnet.py, tests/test_runners/test_dotnet.py
the [launchableinc/nunit](https://github.com/launchableinc/nunit) custom plugin reads a subset(or rest) file and filters tests. 
However, before fixing this change, all test lists are put together by `.`
e.g.) as is
`rocket_car_dotnet.ExampleTest.TestSub.rocket_car_dotnet.ExampleTest.TestMul.`
e.g.) to be
```
rocket_car_dotnet.ExampleTest.TestSub
rocket_car_dotnet.ExampleTest.TestMul
```
So, I fixed it
=> Fix separator and add test

launchable/commands/helper.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py, tests/commands/record/test_session.py
Support `--lineage` option.
e.g)
```
$ launchable record session --build <BUILD NAME> --lineage feature-xxx
```
=> Support lineage option

launchable/commands/record/session.py, launchable/commands/subset.py, launchable/commands/verify.py, launchable/utils/click.py, tests/commands/test_api_error.py
Basically, we should not stop users' CI pipeline. Thus, we should use exit code 0 unless it is an intentional notification. This PR fixes it by catching exception in client.request.
=> Handle exceptions in requests package

launchable/commands/record/build.py, launchable/utils/key_value_type.py, tests/commands/record/test_build.py
The cli collects branch names from git repository information. However, if the `--no-commit-collection` is enabled, cannot collect a branch name.
So, we add a new option `--branch` name.
e.g.)
```sh
$ launchable record build --name <BUILD NAME> \
--no-commit-collection \
--commit a-repo=abc123 \ 
--commit b-repo=56cde \
--branch a-repo=v1.5.2 \
--branch b-repo=v.2.2.4
```
=> Support --branch name option when --no-commit-collection option is enabled

launchable/test_runners/nunit.py, tests/data/nunit/nunit-reporter-bug-with-nested-type.json, tests/data/nunit/nunit-reporter-bug-with-nested-type.xml, tests/data/nunit/output-linux.xml, tests/data/nunit/output-windows.xml, tests/data/nunit/record_test_result.json, tests/data/nunit/src/README.md, tests/data/nunit/src/Test.cs, tests/test_runners/test_nunit.py
* Added nested type to a test case based on NUnit console reporter to make sure it's producing report XML that we expect.
* Added a captured broken test report from launchableinc/nunit that shows how NUnitXML.Logger mishandles nested type
* Improved the nunit profile & the dotnet profile to handle this broken XML in the least invasive way possible
* Added test case to prove the handling of this case.
=> Work around a bug in NUnitXML.Logger mishandling nested type

.github/workflows/python-publish.yml
Currently, we create a tag manually when releasing new changes. We can automate the process by using https://github.com/Songmu/tagpr.
When merging PR, the generated PR by tagpr is created, e.g. https://github.com/ono-max/vscode-launchable/pull/2. We can release new changes only by merging it in the new releasing process.
=> Automate creating tag in releasing process

.github/workflows/python-publish.yml
I tried to release the new version of CLI with tagpr. Unfortunately it was not working correctly. Thus, I need to release https://github.com/launchableinc/cli/releases/tag/v1.71.0  manually.
I enabled workflow_dispatch in release action to release CLI (https://github.com/launchableinc/cli/pull/599). However it’s failed since the version is invalid. https://github.com/launchableinc/cli/actions/runs/5793121929. From my investigation, the version of tag is updated since new change is pushed to master. Thus, we need to checkout tag v1.71.0, but it’s failed in tagpr job (https://github.com/launchableinc/cli/actions/runs/5793167123 ) when running workflow manually with v1.71.0. As a temporary fix, let me ignore tagpr job. After trying it, I’ll revert the change.
=> Ignore tagpr job temporary

.github/workflows/python-publish.yml
Although we can get output between steps, it's not possible to get output directory between jobs. Thus, we need to use `jobs.<job_id>.outputs`.
Ref: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
I confirmed that this works well by releasing my extension with https://github.com/ono-max/vscode-launchable/commit/e3f27aa202cc6788912355dfef3734694463ddc5.
=> Define outputs for retrieving tagpr's output

.github/workflows/python-publish.yml
Currently discord workflow is failed in https://github.com/launchableinc/cli/actions/runs/5793863689/job/15702394002#step:9:15 since the triggered event name for releasing is changed in https://github.com/launchableinc/cli/pull/595. Thus, we need to update the message in discord workflow.
=> Update discord messages

launchable/commands/subset.py, tests/commands/test_subset.py
- Add subset option to prioritize tests failed within XX hours whose 0 <= XX <= 720 (= 24 * 30).
- This can be used to forcibly pick tests that failed in recent hours, such as for a use case like you want pick only tests that failed in the previous nightly test and run them at your work hours to fix the tests.
- The tests picked by this option will be located at the top of the subset.
- The option is inclusively adds tests to subset list, and it may contradict with other exclusive option, such as `--ignore-flaky-tests-above`. To make the rule clear, it is designed to permit only one of inclusive or exclusive to be available. It indicates that you cannot use inclusive `--prioritize-tests-failed-within-hours` option with exclusive `--ignore-flaky-tests-above` option at the same subset …
=> add prioritize_tests_failed_within_hours option

launchable/test_runners/nunit.py, tests/data/nunit/nunit-reporter-bug-with-nested-type.json, tests/data/nunit/nunit-reporter-bug-with-nested-type.xml
Turns out there's another odd behaviour with NUnitXML.Logger that we run into with a customer, which involves the use of TestCase annotation with parameter.
Improved the logic, and added a test case.
=> Fixed a truncation bug in the NUnit profile

launchable/commands/record/tests.py, launchable/commands/subset.py
When the user set both the `--session` option and the `--no-build` option are set, the `--no-build` option, the `--no-build` option will be prioritized now. 
However, if the user set a session value, the CLI should prioritize it, so I fixed it.
=> Add validation when both option --no-build and --session are set

launchable/commands/helper.py, launchable/commands/record/build.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py, tests/commands/test_api_error.py, tests/commands/test_helper.py
This is a follow-up PR for https://github.com/launchableinc/cli/pull/594. Since it seems working now, we can collect telemetry data in other commands, too.
=> Add telemetry for other CLI commands

launchable/commands/subset.py, launchable/utils/tracking.py, tests/commands/test_subset.py
When using both --observation and --output-exclusion-rules options, no output is generated in the standard error. It would be beneficial to inform users about this behaviour.
```shell
$ /Users/ono-max/.local/share/virtualenvs/cli-o7XEfK99/bin/launchable subset --output-exclusion-rules --observation maven src/test/java
WARNING: Both options --observation and --output-exclusion-rules are set. No output will be generated in this case.
Your model is currently in training
Launchable created subset 52 for build sample (test session 46) in workspace launchableinc/mothership
(This test session is under observation mode)
|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset …
```
=> Add validation for scenarios when both --observation and --output-exclusion-rules options are used

launchable/commands/record/build.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/subset.py, launchable/commands/verify.py, launchable/utils/launchable_client.py, launchable/utils/tracking.py
This PR addresses https://github.com/launchableinc/cli/pull/618#discussion_r1309583655. In this update, I've implemented a modification where `get_org_workspace()` method is invoked within `send_error_event` method, effectively preventing redundant calls.
=> Retrieve organization and workspace within send_error_event method

launchable/commands/subset.py, launchable/utils/tracking.py
We have made the decision to classify WARNING event as an error event instead of normal event. Consequently, I have made necessary modifications accordingly.
=> Define Warning as an error instead of normal event

launchable/commands/subset.py, launchable/utils/tracking.py
This PR introduces the `--prioritized-tests-mapping=<string>` option. Users can prioritize tests by specifying this option when loading CLI into the test mapping file.
Here is the format of the file:
```json
{
"format": "prioritized-tests-v1",
"mappings": {
$REPO_NAME: {
$DIRECTORY: [$TEST_PATH, ...],
... // repeatable
},
... // repeatable
}
}
```
* `$REPO_NAME` refers to the repository name provided in `launchable record build --source REPO_NAME=DIR`
* `$DIRECTORY` denotes the relative path within the enclosing repository. If a file under the specified directory is modified, the specified test is prioritized.
* `$TEST_PATH` is the name of a test represented in Launchable's test path notation, such as `class=example.AddTest`.
An actual example following this format is provided below: …
=> Add --prioritized-tests-mapping option

launchable/commands/record/case_event.py, launchable/test_runners/prove.py, tests/data/prove/record_test_result.json, tests/data/prove/report.xml, tests/test_runners/test_prove.py
- This is to remove unnecessary prefix like `1 - ` that happens to be added to the test names produced by [TAP-Formatter-JUnit](https://github.com/bleargh45/TAP-Formatter-JUnit) for Perl Prove.
=> fix prove test report

tests/commands/record/test_attachment.py
Follow up to https://github.com/launchableinc/cli/pull/627
=> [ENG-474] Added a test case for that `record attachment` command

launchable/test_runners/robot.py, tests/data/robot/record_test_executed_only_one_file_result.json, tests/data/robot/single-output.xml, tests/test_runners/test_robot.py
See: https://github.com/launchableinc/cli/issues/637
The robot plugin of the cli was designed with parse logic that assumed multiple `suite` tag. However, when specifying a file like the one below, only one `suite` tag appears, leading to parsing failure
I fixed it and supported both use cases.
Before 
```
$ robot plus.robot
==============================================================================
Plus
==============================================================================
Check method                                                          | FAIL |
0 != -1
------------------------------------------------------------------------------
Plus method                                                           | PASS |
----------------------------------------------------------------- …
```
=> Fix for #637

launchable/test_runners/nunit.py
CLI uses the SAX API instead of the ElementTree API for parsing NUnit, while we commonly use the case ElementTree API for XML parsing. However, it's a little bit hard to extract stdout/stderr if we try to use SAX API. Thus, I've rewritten the parsing logic with ElementTree API.
I'll add the logic to extract stdout/stderr in other PR.
=> Rewrite nunit plugin with ElementTree api

launchable/test_runners/nunit.py, tests/data/dotnet/record_test_result.json, tests/data/nunit/output-linux.xml, tests/data/nunit/output-windows.xml, tests/data/nunit/record_test_result-linux.json, tests/data/nunit/record_test_result-windows.json, tests/data/nunit/src/Test.cs, tests/test_runners/test_nunit.py
Currently, our CLI's nunit plugin does not send stderr. This PR fixes that.
=> Send stderr when recording tests in nunit plugin

launchable/test_runners/robot.py
The `duration` is [datetime.timedelta](https://docs.python.org/3/library/datetime.html#timedelta-objects) object. Then `microseconds` accessor returns just microseconds of the value. In the below case, `microseconds` returns 10.
But we need the total duration of the time. So we changed to use `total_seconds()` method. https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds
```
from datetime import timedelta
delta = timedelta(
days=50,
seconds=27,
microseconds=10,
milliseconds=29000,
minutes=5,
hours=8,
weeks=2
)
delta
datetime.timedelta(days=64, seconds=29156, microseconds=10)
```
=> Fix to use total_seconds() method

launchable/commands/record/build.py, tests/cli_test_case.py, tests/commands/record/test_build.py, tests/commands/test_api_error.py
I was trying to add a new capability here but felt the logic was too complex at this point. A single big function that has tons of local variables, controlling flow of executions in a non-trivial way.
The main idea of this refactoring is:
- Use a single typed `Workspace` object with properties that we are trying to compute, whereas previously this was done by multiple maps keyed by repository names
- Use well-defined sub-functions to split the work into smaller bite-sized chunks, leaving the main logic (L346-356) higher altitude.
In retrospect, this was probably too big to take on without some prior consensus building. So it's OK if we decided not to do this.
If we do choose to move forward, please advise me how best to roll this out a bit slowly & carefully. There appears to be a good …
=> `record build` refactoring

launchable/utils/http_client.py
We set a default time as `(5, 60)` (connection timeout: 5s, read timeout 60s)`. 
However, in the `GET` method, the timeout second as default 60s is a little long. 
So, introduced a `DEFAULT_GET_TIMEOUT` config and use it.
=> introduce default get timeout config

launchable/__main__.py, launchable/app.py, launchable/commands/helper.py, launchable/commands/inspect/subset.py, launchable/commands/inspect/tests.py, launchable/commands/record/attachment.py, launchable/commands/record/build.py, launchable/commands/record/commit.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/split_subset.py, launchable/commands/stats/test_sessions.py, launchable/commands/subset.py, launchable/commands/test_path_writer.py, launchable/commands/verify.py, launchable/utils/commit_ingester.py, launchable/utils/http_client.py, launchable/utils/launchable_client.py, launchable/utils/tracking.py, src/main/java/com/launchableinc/ingest/commits/CommitIngester.java, src/main/java/com/launchableinc/ingest/commits/SSLBypass.java, src/test/java/com/launchableinc/ingest/commits/AllTests.java, src/test/java/com/launchableinc/ingest/commits/BUILD, src/test/java/com/launchableinc/ingest/commits/SSLBypassTest.java
For unblocking a customer, added a switch to disable SSL cert check.
To deal with growing number of global options, promoted the use of the global 'Application' object (formerly called 'AppBase', but to me, that name implied there's something that extends from this base, which is not the case).
=> Refactoring to deal with global configs + SSL cert check bypass

launchable/test_runners/cucumber.py
Current parse logic is a little difficult to read and understand.
So, renamed and defined some methods for easy to read and understand
I didn't edit any test codes, so the result might not changed.
=> Refactor parse test result logics

launchable/utils/link.py, tests/utils/test_link.py
When you have a long list of "View in Jenkins" it's not useful, but the concrete names that they are linking to would allow users to select the right one much more easily.
=> Capture the display name of the URL.

launchable/test_runners/playwright.py, tests/data/playwright/record_test_result.json, tests/data/playwright/report.xml, tests/test_runners/test_playwright.py
Implemented a new plugin for [playwright](https://playwright.dev/)'s junit report.
I tested this plugin at https://github.com/launchableinc/examples/pull/76
Success case: https://github.com/launchableinc/examples/actions/runs/7720959909
Fail case: https://github.com/launchableinc/examples/actions/runs/7720923648/job/21046605819#step:11:15
=> Support playwright's junit reporter format

.editorconfig, src/main/java/com/launchableinc/ingest/commits/CommitGraphCollector.java, src/main/java/com/launchableinc/ingest/commits/ObjectRevFilter.java
Collect head commit, even if it's old
One way we ensure that the CI process integration is working correctly is to make sure all the commits a build refers to are in our possession. This is non-trivial to get right especially when `record build` is run without the commit collection and separate `record commit` is in use.
The intent of filtering by time is to avoid large initial ingestion, so this change is still consistent with that goal.
=> Collect head commit

launchable/__main__.py
By a customer request, even more global switch to disable this check across the whole CI process.
=> Environment variable to skip TLS certificate validation

launchable/test_runners/raw.py, tests/test_runners/test_raw.py
We're going to receive the following JSON in raw profile.
```
{
"testCases": [
{
"testPathComponents": [
{
"type": "file",
"name": "login/test_a.py"
},
{
"type": "class",
"name": "class1"
},
{
"type": "testcase",
"name": "testcase#899"
}
],
"duration": 42,
"status": "TEST_PASSED",
"stdout": "This is stdout",
"stderr": "This is stderr",
"createdAt": "2021-10-05T12:34:00"
}
]
}
```
=> Export test path in raw profile as a structure

launchable/commands/record/build.py
In the push event, GITHUB_HEAD_REF and GITHUB_BASE_REF are empty. In such cases, the git show-ref command is utilized. A complication arises when configuring a branch that contains a slash in the push event. For instance, if the branch name is test/test-branch, the expected value is "test/test-branch," but the current CLI displays "test-branch" instead. This PR resolves this discrepancy.
```
$ python                                   
Python 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> m = re.search('[a-f0-9]{40} refs/heads/(.*)', '65fa86c19329c375cbd5c7649b601e334ba1dea3 refs/heads/foobar/foobar2')
>>> m.group(1)
'foobar/foobar2'
>>> m = …
```
=> Get branch name correctly

src/main/java/com/launchableinc/ingest/commits/CommitGraphCollector.java, src/main/java/com/launchableinc/ingest/commits/CountingDiffFormatter.java
See the linked doc site for more discussion. This solves #786
=> Improve a warning message for missing object errors

launchable/commands/record/tests.py, launchable/test_runners/launchable.py, tests/test_plugin.py
When the Launchable API is down then the cli cannot get a session, the `launchable record tests` command fails with exit code 1. Then, the customer's pipeline will be suspended.
To prevent it, changed to exit 0 when cannot get a session.
```
$ launchable record tests file ./test-results/**/*.xml
File "/Users/yabuki-ryosuke/src/github.com/launchableinc/cli/launchable/commands/record/tests.py", line 223, in tests
session_id = str(find_or_create_session(
File "/Users/yabuki-ryosuke/src/github.com/launchableinc/cli/launchable/commands/helper.py", line 104, in find_or_create_session
saved_build_name = require_build()
File "/Users/yabuki-ryosuke/src/github.com/launchableinc/cli/launchable/commands/helper.py", line 43, in require_build
raise click.UsageError( …
```
=> Exit 0 not to stop a pipeline when `record tests` command cannot get session

launchable/commands/subset.py
```
$  find tests/*.py | launchable subset file > subset.txt
$ cat subset.txt
An error occurred on Launchable CLI. You can ignore this message since the process will continue. Error: No saved build name found.
To fix this, run `launchable record build`.
If you already ran this command on a different machine, use the --session option. See https://www.launchableinc.com/docs/sending-data-to-launchable/using-the-launchable-cli/recording-test-results-with-the-launchable-cli/managing-complex-test-session-layouts/
tests/__init__.py
tests/cli_test_case.py
tests/helper.py
tests/test_plugin.py
tests/test_session.py
tests/test_testpath.py
tests/test_version.py
```
```
$  find tests/*.py | launchable subset file > subset.txt
$ cat subset.txt
tests/__init__.py
tests/cli_test_case.py
tests/helper.py …
```
=> print error message as stderr

tests/cli_test_case.py, tests/test_cli_test_case.py, tests/test_runners/test_raw.py
When comparing a NoneType object and another type, we encountered an error e.g.) `TypeError: '<' not supported between instances of 'NoneType' and 'list'`  and we couldn't use the `assert_json_orderless_equal(self, a, b)` method
So, I fixed it
https://github.com/launchableinc/cli/actions/runs/8390491593?pr=817
=> Fix add metadata

launchable/test_runners/raw.py, tests/cli_test_case.py, tests/test_cli_test_case.py, tests/test_runners/test_raw.py
Launchable started accepting metadata field in each test case. This will provide rich feature in Launchable web console by configuring metadata field. For instance, we plan to provide the feature that users can jump into a test case from Web Console.
As a first step, we'll add metadata field in raw profile.
[58006be](https://github.com/launchableinc/cli/pull/814/commits/58006be7a967a729c4aa3e496fc876a9f2cbf410) is the core logic for adding metadata field in raw profile.
=> Add metadata field in raw profile

launchable/commands/inspect/subset.py, launchable/commands/inspect/tests.py, launchable/commands/record/attachment.py, launchable/commands/record/build.py, launchable/commands/record/session.py, launchable/commands/record/tests.py, launchable/commands/split_subset.py, launchable/commands/stats/test_sessions.py, launchable/commands/subset.py, launchable/commands/verify.py, launchable/utils/launchable_client.py
If the server reports an error, print the payload to assist the troubleshooting. When our service responds, there's JSON payload that contains a quick message. Other HTTP intermediaries may insert other failures, including intermediaries on the customer side.
@Konboi Let me know when is the best time to merge something like this. I'd imagine you might want to push this out past the scheduled maintenance.
=> [UX-171] error message reporting improvement

tests/cli_test_case.py, tests/commands/record/test_attachment.py, tests/commands/record/test_build.py, tests/commands/record/test_commit.py, tests/commands/record/test_session.py, tests/commands/record/test_tests.py, tests/commands/test_api_error.py, tests/commands/test_subset.py, tests/test_runners/test_dotnet.py
Promote the use of more convenient assertion method with  richer error diagnostics
=> Use a convenience method to assert exit code

launchable/test_runners/playwright.py, tests/data/playwright/record_test_result_with_json.json, tests/data/playwright/report.json, tests/test_runners/test_playwright.py
We already provide a "playwright" plugin and support [JUnit reporter](https://playwright.dev/docs/test-reporters#junit-reporter) report. 
However, the JUnit reporter produces the final result of the test even if the test is retried. But [JSON reporter](https://playwright.dev/docs/test-reporters#json-reporter) includes all results when the test're executed multiple times.
So updated to support JSON reporter reports and add the `--json` option.
=> Supports playwright json format report

launchable/commands/record/case_event.py, tests/cli_test_case.py, tests/data/minitest/record_test_result_chunk1.json, tests/data/minitest/record_test_result_chunk2.json, tests/test_runners/test_raw.py
Launchable accepts response as a camel case, not snake case, but CLI sends createdAt as a snake case. This PR addresses the problem.
=> Send createdAt as a camel case

launchable/test_runners/launchable.py, launchable/test_runners/minitest.py, launchable/test_runners/nunit.py, tests/data/minitest/record_test_result.json, tests/data/minitest/record_test_result_chunk1.json, tests/data/minitest/record_test_result_chunk2.json, tests/test_runners/test_googletest.py, tests/test_runners/test_minitest.py
https://github.com/CircleCI-Public/minitest-ci is used for creating test report files. From the following code, it seems to be that a class name is set as a name attribute in testsuite tag.
* https://github.com/CircleCI-Public/minitest-ci/blob/v3.4.0/lib/minitest/ci_plugin.rb#L86-L87
* https://github.com/CircleCI-Public/minitest-ci/blob/v3.4.0/lib/minitest/ci_plugin.rb#L132
Here is a code snippet in minitest. 
```
require 'minitest/autorun'
require "mul"
class TestMul
class Hoge < Minitest::Test
def setup
@mul = Mul.new
end
def test_calc_one
assert_equal @mul.calc(1, 1), 1
end
def test_calc_two
assert_equal @mul.calc(1, 2), 2
end
def test_calc_three
assert_equal @mul.calc(1, 3), 3
end
end
end
```
After executing the above script with minitest-ci, I got the following results. As you can …
=> minitest: Fetch name attribute as a classname

launchable/commands/record/build.py, launchable/test_runners/minitest.py, launchable/test_runners/nunit.py, tests/commands/record/test_build.py
This would allow us to guide the server side behaviour later.
@ono-max can you double check your pre-commit config on this workspace? I had to create 6e5997792783c00a3ba8c720c57494013e36a01f  because my local flake8 run detected unused import statements, which I assume was caused by your recent edits to those files. I expected that when you committed those changes, your pre-commit would have run flake8 that should have fixed them automatically for you.
=> [IB-395] capture the mechanism in which a workspace information was obtained

launchable/commands/helper.py
An experienced customer experiemented with the CLI locally to try out a new command. Upon seeing the --session option, they assumed they just need to pass a test session ID, so they ended up invoking something like `launchable foo bar --session 12345`
That is a good assumption on their part, but it's actually incorrect, as the ID format we take is more complicated. However, there's no error check, so the CLI resulted in 404, which misled them.
By adding parse_session, we can make sure the ID given from the command line is in the correct format, and fail gracefully if not.
=> Error check improvement

tests/cli_test_case.py, tests/data/cucumber/record_test_json_result.json, tests/data/minitest/record_test_result.json, tests/test_cli_test_case.py, tests/test_runners/test_minitest.py
Currently, we do not verify the order of JSON at https://github.com/launchableinc/cli/blob/main/tests/cli_test_case.py#L221 because we evaluate JSON in an order-agnostic manner. However, we aim to ensure the order of test paths is accurate. `assert_json_orderless_equal` disregards the order of items intentionally. Consequently, I have introduced the `assert_test_path_orderly_equal` method to address this requirement, instead of modifying `assert_json_orderless_equal`.
@kohsuke 
I think you designed these methods in https://github.com/launchableinc/cli/pull/91. Can you take a look at this PR?
=> Add assertion to check if the order of test paths is correct

launchable/commands/record/session.py, tests/commands/record/test_session.py
When we introduced a workspace, we expect that customers use a workspace per test suite. However, we  noticed that some customers use a single workspace with multiple test suites. Mixing test suites in a workspace make many features less valuable. For example, trends, test issue triages, test session list, and unhealthy tests are affected. It’s natural to promote “test suites” as a first class data model on Launchable so our customers can sort, filter, and analyze data based on test suites in a workspace.
- Add a new option `--test-suite` to specify a name of test suite executed in a test session.
=> Add --test-suite option to record session

.pre-commit-config.yaml, launchable/test_runners/gradle.py, tests/data/gradle/java/app/src/test/java/com/launchableinc/rocket_car_gradle/App2Test.java, tests/data/gradle/java/app/src/test/java/com/launchableinc/rocket_car_gradle/AppTest.java, tests/data/gradle/java/app/src/test/java/com/launchableinc/rocket_car_gradle/sub/App3Test.java, tests/data/gradle/recursion/expected.json, tests/data/gradle/recursion/foo/bar/reports/1.xml
JUnit 5 has `@Nested` annotation. With the annotation, users can write nested tests. But the nested tests are outputted as `ClassName$InnerClass` style. And Launchable CLI cannot detect the nested test cases on subsetting. So I updated the following changes:
* Update Gradle profile to ignore inner classes
* Update the Gradle demo project with Junit 5
=> Ignore $InnerClass in JUnit 5 and Gradle

launchable/commands/helper.py, launchable/commands/record/tests.py, launchable/commands/subset.py
continue from https://github.com/launchableinc/cli/pull/861
This PR introduces `--test-suite` option to `record tests` and `subset` commands.
=> Add --test-suite option to record tests and subset commands

launchable/test_runners/pytest.py, tests/data/pytest/pytest.ini, tests/data/pytest/record_test_result.json, tests/data/pytest/report.xml, tests/data/pytest/tests/conftest.py, tests/data/pytest/tests/test_funcs1.py, tests/data/pytest/tests/test_funcs2.py
This PR supports https://docs.pytest.org/en/stable/how-to/mark.html in Launchable CLI. Here is an example of an XML file when using marker object.
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite name="pytest" errors="0" failures="4" skipped="0" tests="12" time="0.035"
timestamp="2024-06-13T12:33:48.703447" hostname="ip-192-168-0-28.us-west-2.compute.internal">
<testcase classname="tests.fooo.filenameonly_test" name="test_x"
file="tests/fooo/filenameonly_test.py" line="0" time="0.000" />
<testcase classname="tests.test_funcs1" name="test_func1" file="tests/test_funcs1.py"
line="2" time="0.000">
<properties>
<property name="name" value="foo" />
<property name="args" value="()" />
<property name="kwargs" value="{}" />
</properties>
</testcase>
...
```
=> Support markers in pytest

renovate.json
Want to update these jackson's updates at the same time
https://github.com/launchableinc/cli/pull/848
https://github.com/launchableinc/cli/pull/849
https://github.com/launchableinc/cli/pull/851
So, try to set renovate config ref: https://docs.renovatebot.com/configuration-options/#matchpackageprefixes
=> Set renovate package group rule

tests/commands/test_split_subset.py
I'm not sure why this test was broken by https://github.com/launchableinc/cli/pull/882
But I updated to use `os.path` to assemble file paths
=> fix windowsh path

launchable/test_runners/raw.py, tests/test_runners/test_raw.py
In the raw profile, we used `dict['key']` method with `or <default value>`. However if it doesn't define a target key, a default value won't used and `KeyError: '<TARGET KEY'` exception will be thrown.
So, I fixed to use `.get(<KEY>, <DEFAULT VALUE>)` instead of `dict['key'] or <DEFAULT VALUE>` style.
And, fixed when the user set duration as string type, we'll covert it to float (number)
=> Improve smooth error handling

launchable/commands/record/commit.py, launchable/utils/tracking.py, src/main/java/com/launchableinc/ingest/commits/CommitGraphCollector.java, src/main/java/com/launchableinc/ingest/commits/CommitIngester.java, src/main/java/com/launchableinc/ingest/commits/JSCommit.java, tests/cli_test_case.py, tests/commands/test_api_error.py
Currently, Launchable CLI does not collect commit messages because of security concern, but we'll add the option to collect them since we plan to display commit information in the test session detail page. In the default, we don't collect commit messages.
https://app.launchableinc.com/organizations/demo/workspaces/demov2/data/test-sessions/193372?tab=commits is an example, we'll display the commit message instead of the commit hash if we have the commit message data.
=> Add the option to collect commit messages

launchable/test_runners/playwright.py, tests/data/playwright/record_test_result.json, tests/data/playwright/record_test_result_with_json.json, tests/data/playwright/report.json, tests/data/playwright/report.xml, tests/test_runners/test_playwright.py
Playwright defines the test status type not only "passed","failed", and "skipped" but also "timedOut" and "interrupted".
see: https://playwright.dev/docs/api/class-testresult#test-result-status
However the cli hadn't supported it. So we updated to support the status of "timeOut" and "interrupted"
=> add timedOut test case

launchable/utils/http_client.py
Allow the server side to map which API requests map to which client invocation.
User-agent header can be seen & processed in Datadog. Often we struggle to understand how customers are integrating us in the CI script, and this will give us a key insight.
=> Improve diagnosability

.github/workflows/python-package.yml, tests/cli_test_case.py, tests/commands/test_split_subset.py
=> Fix flaky split test

.github/workflows/python-package.yml
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
* Update the Ubuntu version.
* Stop using Python 3.6 when running CI on Ubuntu.
* https://github.com/actions/setup-python/issues/665
=> Update the Ubuntu version on CI

.github/workflows/e2e.yml
:cry:
- The ubuntu latest (v24) doesn't support python 3.7
- Need go that is newer than v1.23 to install bazelisk
=> Fix e2e part2

Dockerfile
The immediate motivation for the change was from a prospect who had the opsec policy to avoid root in containers. That in turn revealed the problem that the current container is built with venv, a rather odd choise for a container!
It turns out that we probably didn't choose venv because we were clever. Rather, the base image was ubuntu and it disabled/discouraged global pip package installation as it collides with APT.
I could have ignored that warning anyway, but at this point it seems to me that Ubuntu is not helping, it's hurting. So I switched to python:3.x-slim, which appears to be built with the `pip install --global xyz` mindset.
The other key change was to build the package from local source tree, as opposed to install from PyPI. I expect this will be key to automate this into …
=> Redone the dockerfile

Dockerfile, launchable/commands/record/commit.py
This is the problem they run into. Just `print(e)` is a bad idea because it doesn't put them on the right track to solve them.
```
$ launchable record commit 
[Errno 2] No such file or directory: 'git'
```
(In this case, the added injury is that we are requiring `git` that shouldn't really be needed, but I didn't tackle that problem here)
=> Improvement around git-rev-parse

launchable/test_runners/cucumber.py, tests/data/cucumber/report/result.json, tests/test_runners/test_cucumber.py
to ignore it, introduced clean_uri method
=> cucumber json reports sometimes add prefix to uri values

.github/workflows/python-publish.yml
Currently, we manually publish Docker image, but it would be better to automate publishing Docker image using GH Actions because it makes easier to maintain our development workflow.
=> Automate publishing Docker image using GitHub Actions

.github/workflows/python-publish.yml
https://github.com/launchableinc/cli/actions/runs/15527660601/job/43710216131
```
Build summary requires a build reference
Error: buildx failed with: ERROR: invalid tag "cloudbees/launchable\\:v1.101.5": invalid reference format
```
=> [AIENG-168] Fix Docker image tag formatting in workflow

.github/workflows/python-publish.yml
```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```
https://github.com/launchableinc/cli/actions/runs/15527796084/job/43710564284
=> [AIENG-168] Add Docker Buildx setup step to workflow

launchable/test_runners/xctest.py, tests/data/xctest/junit.xml, tests/data/xctest/record_test_result.json, tests/data/xctest/subset_result.json, tests/test_runners/test_xctest.py
Implemented to the XCTest profile. XCTest is the test framework for XCode project ref: https://developer.apple.com/documentation/xctest
This is an example project to try XCTest profile https://github.com/launchableinc/examples/pull/87
Since there aren't any solutions to list test target without executing test, we'll support subset with the [Zero Input Subsetting](https://www.launchableinc.com/docs/features/predictive-test-selection/requesting-and-running-a-subset-of-tests/subsetting-with-the-launchable-cli/zero-input-subsetting/). And we'll use the subset result with `-skip-testing` option of XCTest
```sh
$ launchable subset --target 80% --get-tests-from-previous-sessions --output-exclusion-rules xctest > subset.txt
$ cat $subst.txt
-skip-testing:XCTestSampleTests/XCTestSampleTests …
```
=> Support XCTest 

.github/workflows/python-publish.yml
> The master branch version has been sunset. Please, change the GitHub Action version you use from master to release/v1 or use an exact tag, or opt-in to [use a full Git commit SHA](https://julienrenaux.fr/2019/12/20/github-actions-security-risk/) and Dependabot.
ref: https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#-master-branch-sunset-
GitHub Actions already showed warning(?) message
ref: https://github.com/launchableinc/cli/actions/runs/15556345917
=> deprecated to use master branch

launchable/test_runners/go_test.py, tests/data/go_test/record_test_result.json, tests/data/go_test/reportv1/reportv1.xml, tests/data/go_test/reportv2/reportv2.xml
In Go, we can define subtests like the example below.
However, in the test report, they are shown as a single test case using the format: `test function name / subtest name`.
But when using the `go test -list` command, which is used for subsetting, only the test function names are output—subtest names are not included.
So we need to update the Go test profile to support subtests.
e.g) subtest example
```go
t.Run(tt.title, func(t *testing.T) {...}
```
go test -llist result
```
go test -list="Test|Example" ./...
TestExample1
TestExample2
TestExample3
TestExample4
TestExample5
ok      github.com/launchableinc/examples/go    0.287s
TestGreeting
ExampleGreeting
ok      github.com/launchableinc/examples/go/example    0.475s
```
report example
```xml
<testcase …
```
=> Support subtest case in go-test profile

launchable/utils/file_name_pattern.py, tests/utils/test_file_name_pattern.py
Groovy lang works on JVM but we hadn't set the Groovy to the jvm_test_pattern and the cli couldn't find the test paths.
So we updated the rule.
The cli will be able to do like the below
```sh
launchable subset <OPTIONS> gradle src/test/java src/test/groovy
```
=> Add Groovy config to jvm_test_pattern

launchable/test_runners/maven.py
We supported groovy files with the gradle profile https://github.com/launchableinc/cli/pull/1048. But, I think the maven profile should support groovy too.
So, updated to support groovy files in the maven profile
=> Support groovy file in the maven profile

launchable/test_runners/pytest.py
```
import pytest
@pytest.mark.order(1)
@pytest.mark.dependency(name="a")
@pytest.mark.xfail(reason="deliberate fail")
def test_a():
assert False
@pytest.mark.dependency(name="b")
def test_b():
pass
@pytest.mark.order(2)
@pytest.mark.dependency(name="c", depends=["a"])
def test_c():
pass
@pytest.mark.dependency(name="d", depends=["b"])
def test_d():
pass
@pytest.mark.dependency(name="e", depends=["b", "c"])
def test_e():
pass
```
```
{"pytest_version": "8.4.1", "$report_type": "SessionStart"}
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "tests/test_funcs2.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "tests/test_funcs2.py::test_a", …
```
=> pytest: Enhance JSON report parsing to handle user properties

launchable/commands/verify.py, tests/commands/test_verify.py
This PR addresses the following error:
```
% java -version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
% launchable verify                                    
warnings.warn(
Organization: 'defaulttm'
Workspace: 'my-initial-tests'
Proxy: None
Platform: 'macOS-15.5-arm64-arm-64bit'
Python version: '3.9.6'
Java command: 'java'
launchable version: '1.106.0'
File "/Users/gweerakutti/Library/Python/3.9/bin/launchable", line 8, in <module>
sys.exit(main())
File "/Users/gweerakutti/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1161, in __call__
return self.main(*args, **kwargs)
File "/Users/gweerakutti/Library/Python/3.9/lib/python/site-packages/click …
```
=> Handle error when java -version returns error

launchable/commands/record/tests.py, tests/commands/record/test_tests.py
This outputs a CLI warning if the total test duration is 0 (before rounding) when user executes `launchable record tests`
=> Display a warning if total test duration is 0

launchable/commands/subset.py, launchable/utils/launchable_client.py, tests/cli_test_case.py, tests/commands/test_api_error.py, tests/commands/test_subset.py
To Enable PTS v2 Support
- ~~Add logic to check whether PTS v2 is enabled~~
- ~~When PTS v2 is enabled and no input is provided, enable Zero Input Subset (ZIS) by default~~
- ~~If ZIS has not been computed, automatically list files that look like test files~~
- Add `--get-tests-from-guess` option
=> for PTS v2

launchable/commands/helper.py, launchable/commands/record/attachment.py, launchable/commands/record/tests.py, launchable/commands/subset.py, launchable/utils/session.py, tests/test_session.py
**Before:**
Previously --session flag was not validated when the observation mode is on.
```
% launchable subset --help
Usage: launchable subset [OPTIONS] COMMAND [ARGS]...
Subsetting tests
Options:
.....
--session TEXT                  Test session ID
```
```
% launchable subset --target 25% --session 4785415 --observation gradle src/test/java              
An error occurred on Launchable CLI. You can ignore this message since the process will continue. 
Error: HTTPSConnectionPool(host='api.mercury.launchableinc.com', port=443): Max retries exceeded with url: /intake/organizations/defaulttm/workspaces/my-initial-tests/4785415 (Caused by ResponseError('too many 500 error responses'))
--tests example.MulTest --tests example.Add2Test --tests example.DB1Test --tests example.DB0Test --tests …
```
=> Validate session flag format in subset command

src/main/java/com/launchableinc/ingest/commits/FileChunkStreamer.java, src/test/java/com/launchableinc/ingest/commits/FileChunkStreamerTest.java
revert this change https://github.com/launchableinc/cli/pull/1092/files#diff-3d1f54ea9449652274261178ede80ec176beefebdb4d1d83e84c3f20bf6ccfa0R27
because server side doesn't support this format
=> send only file name instead of repo + file name

src/main/java/com/launchableinc/ingest/commits/CommitGraphCollector.java
This copy/paste error meant the error message was blaming the wrong URL.
=> Error reporting problem

launchable/commands/verify.py, launchable/utils/launchable_client.py
Useful during local development, and for customers who use `$LAUNCHABLE_BASE_URL` to work around their restrictive network environment.
=> Report the endpoint we are talking to

tests/commands/test_api_error.py, tests/utils/test_http_client.py
```
======================================================================
FAIL [1.113s]: test_all_workflow_when_server_down (tests.commands.test_api_error.APIErrorTest.test_all_workflow_when_server_down)
----------------------------------------------------------------------
File "/home/runner/.local/share/virtualenvs/smart-tests-cli-djAcMpSV/lib/python3.11/site-packages/responses/__init__.py", line 232, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/unittest/mock.py", line 1831, in _inner
return f(*args, **kw)
^^^^^^^^^^^^^^
File "/home/runner/work/smart-tests-cli/smart-tests-cli/tests/commands/test_api_error.py", line 440, in test_all_workflow_when_server_down …
```
=> Fix CI on the v1 branch

tests/utils/test_http_client.py
Adresses https://github.com/cloudbees-oss/smart-tests-cli/pull/1135/files/e93eed7c54af2d488ec1d9b945f756f148685182#r2350860020
=> Remove a useless test - HttpClientTest#test_reason

launchable/commands/subset.py
The name is still subject to change
=> [AIENG-230] defined a switch to control the test selection behavior

README.md, launchable/commands/helper.py, launchable/commands/subset.py, launchable/utils/launchable_client.py
Updating URLs to point to the new home.
Old URLs are getting redirected to the new ones anyway, but this way we have one less thing to rely on
=> [AIENG-222] Doc site update
