launchable/commands/record/build.py
launchable/utils/http_client.py
setup.py

To became API base URL replaceable, I introduced LaunchableClient.
- Add LaunchableClient
- Add LAUNCHABLE_BASE_URL environment variable

Add LaunchableClient and LAUNCHABLE_BASE_URL env

---

.github/workflows/python-package.yml
launchable/commands/record/case_event.py
launchable/commands/record/test.py

- Recording `file`, `classname`, `timestamp`, `lineno` when the CLI sends test cases

Recording test paths

---

launchable/commands/record/__init__.py
launchable/commands/record/session.py
launchable/commands/record/test.py
launchable/commands/verify.py

`optimize test` command need `session_id` before recording test results. Therefore split session creation request from `record test` command.
`record session` command is used like this;
```shell
$ LAUNCHABLE_TEST_SESSION=$(launchable record session --name 123)             
$ rails test $(launchable optimize test $(find test -regex .*_test.rb | tr "\n" " ") --name 123 --session $LAUNCHABLE_TEST_SESSION)
$ launchable record test test.xml --name 123 --session $LAUNCHABLE_TEST_SESSION
```

Add record session command

---

launchable/commands/optimize/tests.py
launchable/test_runners/bazel.py
launchable/test_runners/generic.py

Send test paths in the `launchable optimize test`. 
For example,
```json
[{ 
"type": "file", 
"name": "test/models/admin/user_test.rb"
}]

Send test paths in the optimize tests command

---

launchable/test_runners/bazel.py

#69 depended on some other commits. This PR cherry-picked only #69 commits.

Cherry-pick #69 commits

---

launchable/test_runners/minitest.py

#68 depended on some other commits. This PR cherry-picked only #68 commits.

Cherry-pick #68

---

launchable/commands/subset.py

Follow up to #67.
Implemented this as per our discussion.

Optimize test file path

---

launchable/commands/record/build.py
launchable/commands/record/commit.py
launchable/commands/record/session.py
launchable/commands/record/tests.py
launchable/commands/subset.py
launchable/test_runners/minitest.py

... as I was writing the documentation: https://github.com/launchableinc/mothership/pull/1007

One more round of touch-ups

---

launchable/test_runners/googletest.py

This is a quick fix according to the comments on https://github.com/launchableinc/cli/pull/79

Quick fix for #79

---

launchable/utils/gzipgen.py
tests/test_version.py
tests/utils/test_gzipgen.py

Might as well keep this now that I wrote it.

Added a quick test case to show gzipgen is working

---

launchable/commands/verify.py
launchable/utils/click.py
launchable/utils/token.py
tests/commands/test_verify.py

* Check the version of Java & Python, not just the existence
* Deal gracefully in environments that do not support Unicode emoji

"launchable verify" improvements

---

tests/test_runners/test_gradle.py

fix: test name

---

tests/data/googletest/output_a.xml
tests/data/googletest/output_b.xml
tests/data/googletest/record_test_result.json
tests/test_runners/test_googletest.py

- Add googletest result files
- Add record test's unit test for googletest

[ST-700] add unit test for googletest record tests

---

launchable/commands/record/build.py
launchable/commands/record/tests.py

This fixes the warning from SLF4J

[ST-644] integrating the new ingester jar

---

tests/data/googletest/subset_result.json
tests/test_runners/test_googletest.py

[ST-700] add unit test for gooletest's subset

---

launchable/commands/record/tests.py

Added session closing to the record test command.

Close the test session at the end of event sending.

---

tests/cli_test_case.py
tests/test_runners/test_go_test.py

Add closing session tests

---

launchable/commands/verify.py

Fix the verify command to show an organization and a workspace name

---

launchable/test_runners/maven.py
tests/data/maven/java/test/src/java/com/launchableinc/rocket_car_maven/App2Test.java
tests/data/maven/java/test/src/java/com/launchableinc/rocket_car_maven/AppTest.java
tests/data/maven/record_test_result.json
tests/data/maven/reports/1.xml
tests/data/maven/reports/2.xml
tests/data/maven/subset_result.json
tests/test_runners/test_maven.py

SSIA
I wrote the document in another PR https://github.com/launchableinc/cli/pull/119, so please see it if you know the useage.

[ST-732] Maven plugin

---

docs/SUMMARY.md
docs/getting-started.md
docs/integrations/README.md
docs/integrations/maven.md

[ST-732] doc for the maven plugin

---

docs/integrations/cypress.md

I was wrong about a link in the cypress doc.

Fix link in a doc

---

tests/test_runners/test_maven.py

to avoid order problem

---

docs/getting-started.md

`record build` doesn't have `--build` option. The correct option is `--name`.

Fix record build option name

---

launchable/commands/record/commit.py
tests/commands/record/test_commit.py

This PR will propose after Ingerster PR merged.

Add proxy support in `record commit` command

---

docs/SUMMARY.md
docs/resources/convert-to-junit.md
docs/resources/troubleshooting.md
docs/security/data-examples.md
docs/security/data-privacy-and-protection.md

These were captured by running commands locally through a proxy. Soon we will have an audit log; in the meantime, this is intended to answer infosec questions about what we collect.

Add example POST bodies

---

launchable/test_runners/behave.py
tests/data/behave/record_test_result.json
tests/data/behave/reports/report.xml
tests/data/behave/subset_result.json
tests/test_runners/test_behave.py

I support [behave](https://pypi.org/project/behave/) as a python BDD test library.
refs: #162

[ST-821] support behave runner

---

docs/optimizing-test-execution/subsetting-tests.md
docs/resources/integrations.md
docs/training-a-model/recording-test-results.md

[ST-821] add documentation for behave

---

tests/data/behave/record_test_result.json

A test on the latest `main` branch is failed. I removed `_lineno` from a test data file to fix it.

Fix a failed test

---

launchable/test_runners/minitest.py
launchable/test_runners/rspec.py
tests/data/rspec/record_test_result.json
tests/data/rspec/rspec.xml
tests/test_runners/test_gradle.py
tests/test_runners/test_rspec.py

Added the Rspec plugin, which is almost the same as minitest.
I found a bug in minitest and fixed it.

add rspec plugin

---

docs/optimizing-test-execution/subsetting-tests.md
docs/resources/integrations.md
docs/training-a-model/recording-test-results.md

[ST-828] doc for robot plugin

---

tests/test_runners/test_robot.py

[ST-828] add robot plugin's test

---

launchable/commands/record/tests.py
launchable/commands/subset.py
launchable/utils/http_client.py
tests/utils/test_http_client.py

set test-runner name when cli requests to the API.

[ST-839] set test framework  name to header

---

docs/test-runners/robot.md

add test command used by subset result

---

docs/getting-started.md
docs/resources/integrations.md
docs/test-runners/rspec.md

add doc for RSpec plugin

---

docs/test-runners/minitest.md

See: https://github.com/launchableinc/cli/pull/180#discussion_r602217425

modify minitest doc. Add description for minitest-ci.gem

---

launchable/commands/record/session.py
launchable/commands/subset.py
tests/commands/record/test_session.py

API starts to support flavor option for create test session, so cli supports it

[ST-872] add flavor option for create test session

---

launchable/commands/record/tests.py

support the record tests command too,

support flavor option to the record tests command

---

launchable/commands/subset.py

I fixed check logic 
https://github.com/launchableinc/cli/pull/188#discussion_r609786684

[ENG-50] fix check logic

---

README.md
launchable/utils/http_client.py

Enable `--log-level debug` to see all the response headers from the server.

Debug headers

---

.github/workflows/python-package.yml
launchable/commands/record/case_event.py
launchable/test_runners/bazel.py
launchable/utils/session.py
setup.cfg
tests/cli_test_case.py
tests/commands/record/test_tests.py
tests/test_runners/test_gradle.py

Enable to run `launchable subset` and `launchable record test` on Windows.
* Use [Win32_LogonSession](https://powershell.one/wmi/root/cimv2/win32_logonsession) as a session id
* Canonicalize path name in TestPath with `replace("\\", "/")`
* Add Windows runner on GitHub Action
* Fixed some tests

Windows support

---

docs/test-runners/go-test.md

`go test -list` needs regex and pathes

Fix Go doc

---

docs/test-runners/TEMPLATE.md
docs/test-runners/ant.md
docs/test-runners/bazel.md
docs/test-runners/behave.md
docs/test-runners/ctest.md
docs/test-runners/cypress.md
docs/test-runners/go-test.md
docs/test-runners/googletest.md
docs/test-runners/gradle.md
docs/test-runners/maven.md
docs/test-runners/minitest.md
docs/test-runners/nose.md
docs/test-runners/robot.md
docs/test-runners/rspec.md

...Then come back to subsetting.

Reorder instructions to make sure tests get recorded first

---

launchable/commands/record/build.py
launchable/commands/record/session.py
launchable/commands/record/tests.py
launchable/commands/subset.py
launchable/utils/http_client.py
launchable/utils/logger.py

e.g) subset request
before
```
AUDIT:launchable:send request method:post path:/intake/organizations/org/workspaces/ws/subset headers:{'Content-Type': 'application/json', 'Content-Encoding': 'gzip'} args:{'data': b'\x1f\x8b\x08\x00\x9e\xdb\x94`\x02\xff\xabV*I-.\tH,\xc9(V\xb2R\x88\x8e\xd5QP*N-.\xce\xcc\xcf\x03r\xab\x952S\x80\x94\x92\xa1\xa5\x85R-P\xa6$\xb1(=\xb5\x04(b\xa0gX\x0b\x00\xb5\x04\x9c\xb2:\x00\x00\x00', 'timeout': (5, 180)}
```
after 
```
AUDIT:launchable:send request method:post path:/intake/organizations/org/workspaces/ws/subset headers:{'Content-Type': 'application/json', 'Content-Encoding': 'gzip'} args:{'data': '{"testPaths": [[{"type": "class", "name": "com.example.package.App2Test"}], [{"type": "class", "name": "com.example.package.AppTest"}]], "session": {"id": "198"}, …
```

[ENG-111] decompress data when request payload is compressed

---

docs/resources/cli-reference.md
launchable/commands/record/build.py
launchable/commands/record/commit.py
setup.cfg

Added max-days option so that users can collect commits older than 30 days.

Add max-days option

---

launchable/test_runners/gradle.py

Intended for more advanced scripted integration with Gradle

Option to just add class names without '--tests' prefix

---

launchable/test_runners/nunit.py
tests/test_runners/test_nunit.py

Assembly name shouldn't be a part of the test name

NUnit support bug fix

---

docs/SUMMARY.md
docs/languages/dotnet.md
docs/test-runners/README.md
docs/test-runners/nunit.md

Adding NUnit documentation

---

docs/resources/cli-reference.md

add doc for confidence base subsetting

---

launchable/commands/record/tests.py

When the report files were skipped, it is difficult for us to notice that. 
So I added new warning message

Add warning message when the report files were skipped

---

launchable/test_runners/launchable.py
launchable/test_runners/minitest.py
launchable/test_runners/rspec.py

What we discussed today -- promote more code reuse between different test runners

Promote reuse of test runner support code

---

docs/SUMMARY.md
docs/getting-started.md
docs/subset-your-tests.md
docs/test-runners/TEMPLATE.md
docs/test-runners/adb.md
docs/test-runners/ant.md
docs/test-runners/bazel.md
docs/test-runners/behave.md
docs/test-runners/ctest.md
docs/test-runners/cypress.md
docs/test-runners/go-test.md
docs/test-runners/googletest.md
docs/test-runners/gradle.md
docs/test-runners/maven.md
docs/test-runners/minitest.md
docs/test-runners/nose.md
docs/test-runners/nunit.md
docs/test-runners/robot.md
docs/test-runners/rspec.md

This is just an MVP. I'll come back and improve this tomorrow.

Add a 'stub' subsetting page so we can link to it from the webapp

---

docs/resources/integration-for-open-source.md

I added documentation on tokenless authentication

[ENG-181] Add documentation for tokenless authentication

---

launchable/commands/verify.py

From a recent interaction with an user who struggled through getting the proxy setting right came this change.
- I'm generally a fun of more information when things go wrong. When the verify command fails, the user is clearly hitting some blocking problem and so added details can save a lot of frustrating time. So when the verify command fails, report a full stack trace.
- Report the proxy that we are using, to help people verify that their proxy setting is correctly recognized by us.

Improved the error diagnostics

---

docs/SUMMARY.md

Link to the new OSS page

---

docs/sending-data-to-launchable.md

Fix a doc link

---

.github/workflows/python-package.yml

split test step to notice fail faster

---

launchable/utils/http_client.py
tests/utils/test_http_client.py

rm bracket

---

docs/resources/integrations/pytest.md

Add documentation about pytest's junit format
See: https://github.com/launchableinc/cli/pull/297

Add documentation about pytest's junit format

---

docs/resources/integrations/ctest.md

Wait until https://github.com/launchableinc/cli/pull/303 is released.

Update the ctest profile usage

---

docs/sending-data-to-launchable/use-flavors-to-run-the-best-tests-for-an-environment.md

* Usage with `launchable record session` is now covered
* Improve examples

--flavor docs improvements

---

launchable/test_runners/jest.py
tests/data/jest/junit.xml
tests/data/jest/record_test_result.json

From a customer's feedback, we decided to record class names in the Jest plugin.

Jest plugin reacords class names

---

docs/resources/integrations/jest.md

Add [jest-junit](https://www.npmjs.com/package/jest-junit) configs that export class names.

Improve Jest.md to support #329

---

.github/workflows/python-package.yml

To prevent duplicate sessions (unsure why this is occurring).

Manually create a Launchable session

---

launchable/commands/record/build.py
launchable/commands/record/commit.py

Add an option to scrub PIIs

---

docs/resources/integrations/cucumber.md

I wrote a document for a cucumber plugin.

add document

---

launchable/commands/record/tests.py

- fix multiple returning values to Tuple type

fix return multiple value as tuple

---

README.md

update readme; add installation

---

launchable/commands/helper.py
launchable/commands/record/build.py
launchable/commands/record/session.py
launchable/commands/record/tests.py
launchable/commands/split_subset.py
launchable/commands/subset.py
launchable/test_runners/launchable.py
launchable/utils/click.py
launchable/utils/http_client.py

- clarify some argument types by adding type hinting
- to improve readability

refactor to add some type hinting for readability

---

docs/resources/integrations/go-test.md

Fix doc go test

---

launchable/commands/record/tests.py

I was inspecting how two different test results compare wrt Launchable,
and it turns out a handy way to do so is to have the CLI print out test
paths, and compare them.
This seems like a reasonable diagnostic capability, so I'm keeping it.

Added a debug switch to just report test paths.

---

launchable/commands/record/tests.py
launchable/test_runners/cucumber.py
tests/test_runners/test_cucumber.py

I use the file path from the report json file directly. But it's depended on user argument.
So, I changed to use make_file_path_component method not to affect user arguments.

Use FilePathNormalizer to make test path

---

launchable/commands/record/build.py
launchable/commands/record/commit.py

Fix commit collect error handling

---

launchable/commands/subset.py

- escape when subset not in summary.

fix subset in dict

---

launchable/commands/record/tests.py

Print url to open web app test session details page in launchable record tests command

show web app page

---

launchable/commands/inspect/subset.py
launchable/commands/inspect/tests.py
launchable/commands/subset.py

- use `get` to get key from dict

fix dict to get key by get

---

tests/commands/test_api_error.py

Check not to disrupt user's CI job when Launchable returns error

Test when Launchable returns error

---

launchable/commands/record/commit.py
launchable/test_runners/pytest.py

Reverts launchableinc/cli#389
- Github actions failing

Revert "Fix/vulnerability"

---

launchable/commands/record/commit.py
launchable/test_runners/pytest.py

- fix vulnerability
- int to str
- https://github.com/launchableinc/cli/pull/389

fix vulnerability and int to str

---

launchable/commands/record/commit.py
launchable/test_runners/pytest.py

Revert "fix vulnerability and int to str"

---

.github/workflows/e2e.yml
launchable/commands/record/commit.py
launchable/test_runners/pytest.py

- fix os command vulnerability
- trigger e2e test github actions on PR to main branch
- https://github.com/launchableinc/cli/pull/389
- https://github.com/launchableinc/cli/pull/390
- https://github.com/launchableinc/cli/pull/391
- https://github.com/launchableinc/cli/pull/392

fix vulnerability subprocess

---

docs/resources/cli-reference.md

record commit --source doesn't support the repo name

---

launchable/commands/subset.py

- fix subset output bug.
```
|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |            7 |                      100 |                0.000116667 |
| Remainder |            0 |                        0 |                0           |
|           |              |                          |                            |
| Total     |            7 |                      100 |              100           |
```
```
|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |            7 |                      100 |                0.000116667 …
```

fix output bug

---

docs/resources/integrations/maven.md

Explaining how to use https://github.com/launchableinc/testng/ for Maven+TestNG subsetting.

Documented the TestNG support in subsetting

---

launchable/test_runners/go_test.py
tests/data/go_test/subset_result.json

Without this, it won't make a subset request in the proper altitude.

Fix Go Test Profile

---

.github/workflows/python-package.yml

ignore file for test codes

---

.github/workflows/publicize-doc-change.yml

We should be all aware of what's changing the doc

Post to Slack channel when docs change

---

docs/resources/integrations/maven.md

... which is standard for most real world multi-module setup.

Example should show multiple createdFiles.lst

---

launchable/utils/git_log_parser.py

This adds a line number to the git log parsing error messages.

Tell which line is failed to parse

---

docs/resources/integrations/go-test.md
docs/resources/integrations/gradle.md
docs/resources/integrations/pytest.md

- Example integration of Launchable to GitHub Actions in go-test, gradle and pytest.

add sample github actions integration to go, gradle and pytest

---

docs/resources/integrations/raw.md
launchable/commands/record/tests.py
launchable/test_runners/raw.py
tests/test_runners/test_raw.py

Currently the raw profile only takes a JSON file. This change make it
take a JUnit XML file.

Teach the raw profile to take a JUnit XML file

---

docs/sending-data-to-launchable/migration-to-github-oidc-auth.md

The permissions cannot be added to the step.

Fix the GitHub Actions permission config

---

launchable/commands/record/tests.py

- Add hidden option to record test to allow sending a test report created before record build.

Add option to allow sending test report before build

---

launchable/test_runners/maven.py
tests/test_runners/test_maven.py

support --same-bin for maven profile

---

launchable/commands/record/build.py
launchable/commands/verify.py
launchable/test_runners/adb.py
launchable/test_runners/go_test.py
launchable/test_runners/googletest.py
launchable/utils/sax.py

- Compile regular expression pattern beforehand if it is used repeatedly. This should improve performance a bit.

use re.compile for regexp

---

launchable/commands/split_subset.py

- This PR is to validate subset ID in the split subset request to ensure the value exists, and cannot be null.

Fix subsetting

---

launchable/commands/record/case_event.py

- Add if-else statement to make the duration always positive or 0.0 if it happens to be negative.

fix duration to be always positive or 0

---

launchable/test_runners/raw.py
tests/test_runners/test_raw.py

The raw profile can't receive multiple report files, so I fixed supporting multiple report files.

support multiple files

---

launchable/commands/record/session.py

- This is from https://github.com/launchableinc/cli/pull/552 .
- Since a forked external branch cannot pass Github actions, I merged the original PR to Launchable's branch, and then run the actions.

Fix no newline

---

launchable/commands/record/build.py
tests/cli_test_case.py
tests/commands/record/test_build.py

```
awilkes@MacBook-Pro-2 cli % python3 -m launchable record build --name foo03172
Launchable recorded 2 commits from repository /Users/awilkes/code/launchable/cli
Launchable recorded build foo03172 to workspace launchableinc/awilkes with commits from 1 repository:
| .      | .      | 6ce5dd86412c9c3010803cedeaad21b248143708 |
Visit https://app.launchableinc.com/organizations/launchableinc/workspaces/awilkes/data/builds/1647218 to view this build and its test sessions
```

Link to build from CLI output

---

launchable/commands/subset.py

Kept the historical one for backward compatibility.

Better, more consistent option name.

---

.github/workflows/e2e.yml
Pipfile
launchable/commands/record/commit.py

Working toward re-releasing v1.67.0, the last known good version, as v1.67.2

Reverted all the changes from v1.67.0 -> v1.67.1 for emergency fix

---

.github/workflows/python-package.yml
README.md

The CI may be broken someday. We need to check the status of CI by running it daily.

Run CI daily

---

launchable/commands/record/tests.py
launchable/commands/subset.py
launchable/commands/test_path_writer.py
launchable/test_runners/nunit.py
launchable/testpath.py
launchable/utils/click.py
launchable/utils/git_log_parser.py
launchable/utils/sax.py

- Fix type hinting to Python >= 3.6.

fix outdated type hintings

---

.github/workflows/python-publish.yml

I confirmed this works in https://github.com/ono-max/vscode-launchable/commit/37519472ad111fc22e8eeb12527e24bca612c19a.

Add the ability to publish CLI with workflow_dispatch

---

.github/workflows/python-publish.yml

followup fix for launchableinc/cli#602

---

.github/workflows/python-publish.yml

Reverts https://github.com/launchableinc/cli/pull/603 and https://github.com/launchableinc/cli/pull/602.

Revert changes in Github Actions

---

launchable/utils/launchable_client.py

The api pf HTTP error event value was fixed as "verification". So, I fixed to use an url path

fix api values

---

launchable/commands/subset.py

extend timeout duration

---

launchable/commands/record/session.py
launchable/commands/verify.py
tests/commands/record/test_session.py

I've forgotten to add telemetry when the exist code is 2. This PR addresses it.

Add telemetry when the exit code is 2

---

launchable/utils/launchable_client.py

minor refactoring to make the code more DRY

Made more DRY

---

.pre-commit-config.yaml
launchable/commands/helper.py
launchable/commands/record/__init__.py
launchable/commands/record/attachment.py
launchable/utils/http_client.py
launchable/utils/launchable_client.py

* Change in `http_client.py` to support sending `BinaryIO` as the payload, with streaming compression support
* Bit of refactorying in `helper.py` to introduce `require_session()` for CLI commands that require a session to be given or present

[ENG-474] new command to attach logs to a test session

---

.github/workflows/python-package.yml

This is inspired by https://github.com/launchableinc/nose-launchable/pull/70.

Retry installation step if it's failed

---

launchable/commands/record/build.py

define with type

---

launchable/test_runners/cucumber.py
tests/data/cucumber/record_test_json_result.json
tests/data/cucumber/report/result.json
tests/test_runners/test_cucumber.py

Cucumber has two types of hooks: step hooks and scenario hooks. When step hooks are executed, the information is registered for each step. Conversely, when scenario hooks are executed, the information is registered for each element. This PR handles both cases.

Handle cucumber hooks information correctly

---

.github/workflows/python-package.yml

update actions version

---

.github/workflows/python-package.yml
Pipfile

Add Python version 3.11, 3.12

---

.github/workflows/e2e.yml
.github/workflows/python-package.yml
.github/workflows/python-publish.yml

update to v5

---

.github/workflows/bazel-test.yml

Introduce a `bazel test` workflow to merge updating PRs
e.g.)
- https://github.com/launchableinc/cli/pull/668
- https://github.com/launchableinc/cli/pull/669
Sample action: https://github.com/launchableinc/cli/actions/runs/7319257445/job/19936904892

Setup bazel test

---

.github/workflows/python-package.yml

Don't have to execute python test when exe.jar related files changed

---

launchable/commands/helper.py

* Removed duplicate code that appear to be a result of a refactoring error or merge failure
* Fixed a broken link in error message

Misc update

---

.github/workflows/e2e.yml

set distribution to setup-java

---

.github/workflows/e2e.yml

from setup-java v4, changed the format

---

tests/cli_test_case.py
tests/commands/test_api_error.py
tests/commands/test_split_subset.py
tests/commands/test_subset.py
tests/test_runners/test_adb.py
tests/test_runners/test_ant.py
tests/test_runners/test_bazel.py
tests/test_runners/test_behave.py
tests/test_runners/test_ctest.py
tests/test_runners/test_cts.py
tests/test_runners/test_cucumber.py
tests/test_runners/test_cypress.py
tests/test_runners/test_dotnet.py
tests/test_runners/test_go_test.py
tests/test_runners/test_googletest.py
tests/test_runners/test_gradle.py
tests/test_runners/test_jest.py
tests/test_runners/test_maven.py
tests/test_runners/test_minitest.py
tests/test_runners/test_nunit.py
tests/test_runners/test_prove.py
tests/test_runners/test_pytest.py
tests/test_runners/test_raw.py
tests/test_runners/test_robot.py
tests/test_runners/test_rspec.py

Use this convenience method, which prints out the CLI output in case on an unexpected error.

Test refactoring

---

launchable/commands/record/session.py
launchable/commands/record/tests.py

There's a question about the wisdom of importing a private function

Improved error diagnostics

---

launchable/test_runners/launchable.py
tests/commands/test_api_error.py

Alternative solution for https://github.com/launchableinc/cli/pull/761.

Do not stop pipeline in record test command

---

launchable/test_runners/launchable.py

Follow-up to https://github.com/launchableinc/cli/pull/790

Add a comment for readability

---

launchable/utils/http_client.py

fix type check

---

launchable/commands/record/commit.py
launchable/utils/tracking.py

We'd like to track the repository is shallow repository in the perspective of CSM.

Track shallow clone

---

launchable/commands/record/tests.py

fix option name

---

tests/test_runners/test_playwright.py

fix val name

---

launchable/test_runners/robot.py
setup.cfg

junitparser library has changed the behavior by this PR https://github.com/weiwei/junitparser/pull/142 and this change was shipped as v4.0.0. The robot profile affected the change. 
So, I updated the require junitparser version and followed the new behavior

Fix robot ci failure

---

smart_tests/commands/record/build.py

As @Konboi and I discussed before, make `--branch` optional.

Make `--branch` optional

---

launchable/commands/record/commit.py

The caller side was not removed. Oof.

Follow up fix to f85f624d3816716a220bcd4123edad30ce88babc

---

.github/workflows/publish.yml
Dockerfile

Configure the Dockerfile to ship ` cloudbees/smart-tests-cli` docker image

Migrate Docker setting with smart tests

---

.github/workflows/e2e.yml
.github/workflows/python-package.yml
.github/workflows/python-publish.yml
.tagpr

I changed the following setting for `v1` branch.
* tagpr
* CI

Update CI config files for Launchable CLI v1 branch
